# Generated by Django 5.2.3 on 2026-01-22 14:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the user', primary_key=True, serialize=False, unique=True)),
                ('username', models.CharField(blank=True, db_index=True, help_text='Auto-generated username for client users only', max_length=255, null=True, unique=True)),
                ('name', models.CharField(blank=True, db_index=True, help_text='Full name (optional for clients, required for PPPoE)', max_length=255, null=True)),
                ('email', models.EmailField(blank=True, db_index=True, help_text='Email address for authenticated users only', max_length=255, null=True, unique=True)),
                ('phone_number', models.CharField(blank=True, db_index=True, help_text='Phone number for client users only (+254 format)', max_length=20, null=True, unique=True)),
                ('user_type', models.CharField(choices=[('client', 'Client'), ('staff', 'Staff'), ('admin', 'Admin')], db_index=True, default='client', max_length=20)),
                ('connection_type', models.CharField(choices=[('hotspot', 'Hotspot'), ('pppoe', 'PPPoE')], db_index=True, default='hotspot', help_text='Connection type for client users only', max_length=20)),
                ('source', models.CharField(choices=[('admin_dashboard', 'Admin Dashboard'), ('captive_portal', 'Captive Portal'), ('api', 'API'), ('system', 'System')], db_index=True, default='admin_dashboard', help_text='Source of user creation', max_length=20)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('pppoe_username', models.CharField(blank=True, db_index=True, help_text='PPPoE username (auto-generated for PPPoE clients)', max_length=50, null=True, unique=True)),
                ('pppoe_password', models.TextField(blank=True, help_text='Encrypted PPPoE password', null=True)),
                ('pppoe_active', models.BooleanField(db_index=True, default=False)),
                ('pppoe_credentials_generated', models.BooleanField(db_index=True, default=False)),
                ('pppoe_credentials_generated_at', models.DateTimeField(blank=True, null=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('last_login', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User Account',
                'verbose_name_plural': 'User Accounts',
                'ordering': ['-date_joined'],
                'indexes': [models.Index(fields=['user_type', 'is_active'], name='authenticat_user_ty_c1ae22_idx'), models.Index(fields=['email', 'is_active'], name='authenticat_email_c7b1aa_idx'), models.Index(fields=['phone_number', 'is_active'], name='authenticat_phone_n_e597e9_idx'), models.Index(fields=['pppoe_username', 'pppoe_active'], name='authenticat_pppoe_u_70c764_idx'), models.Index(fields=['date_joined'], name='authenticat_date_jo_b4dd80_idx'), models.Index(fields=['source'], name='authenticat_source_81e01c_idx'), models.Index(condition=models.Q(('user_type', 'client')), fields=['user_type'], name='idx_client_users'), models.Index(condition=models.Q(('connection_type', 'pppoe')), fields=['connection_type'], name='idx_pppoe_users'), models.Index(condition=models.Q(('is_active', True)), fields=['is_active'], name='idx_active_users'), models.Index(condition=models.Q(('source', 'captive_portal')), fields=['source'], name='idx_captive_users')],
            },
        ),
    ]
