# Generated by Django 5.2.3 on 2025-09-19 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='is_2fa_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
