# Generated by Django 5.2.3 on 2026-01-28 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='connection_type',
            field=models.CharField(choices=[('hotspot', 'Hotspot'), ('pppoe', 'PPPoE'), ('admin', 'Admin')], db_index=True, default='hotspot', help_text='Connection type for client users only', max_length=20),
        ),
    ]
