# Generated by Django 5.2.3 on 2026-01-28 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_useraccount_connection_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='email',
            field=models.EmailField(blank=True, db_index=True, help_text='Email address for authenticated users only (optional for clients)', max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='source',
            field=models.CharField(choices=[('djoser_registration', 'Djoser Registration'), ('admin_dashboard', 'Admin Dashboard'), ('captive_portal', 'Captive Portal'), ('api', 'API'), ('system', 'System')], db_index=True, default='djoser_registration', help_text='Source of user creation', max_length=20),
        ),
    ]
