# Generated by Django 5.2.3 on 2025-09-20 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('authentication', '0003_alter_useraccount_client_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useraccount',
            options={'ordering': ['-date_joined']},
        ),
        migrations.AddField(
            model_name='useraccount',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='useraccount',
            index=models.Index(fields=['date_joined'], name='authenticat_date_jo_b4dd80_idx'),
        ),
        migrations.AddIndex(
            model_name='useraccount',
            index=models.Index(fields=['last_updated'], name='authenticat_last_up_93e4cb_idx'),
        ),
    ]
