# Generated by Django 5.2.3 on 2025-11-28 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('authentication', '0004_alter_useraccount_options_useraccount_last_updated_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='useraccount',
            name='authenticat_user_ty_c1ae22_idx',
        ),
        migrations.AddField(
            model_name='useraccount',
            name='connection_type',
            field=models.CharField(choices=[('hotspot', 'Hotspot'), ('pppoe', 'PPPoE'), ('admin', 'Admin Portal')], db_index=True, default='hotspot', max_length=20),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='last_pppoe_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='pppoe_active',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='pppoe_ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='pppoe_password',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='pppoe_username',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='useraccount',
            index=models.Index(fields=['user_type', 'connection_type', 'is_active'], name='authenticat_user_ty_814dc5_idx'),
        ),
        migrations.AddIndex(
            model_name='useraccount',
            index=models.Index(fields=['pppoe_username', 'pppoe_active'], name='authenticat_pppoe_u_70c764_idx'),
        ),
        migrations.AddIndex(
            model_name='useraccount',
            index=models.Index(fields=['connection_type', 'is_active'], name='authenticat_connect_47e7c0_idx'),
        ),
    ]
