# Generated by Django 5.2.3 on 2025-11-30 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('authentication', '0005_remove_useraccount_authenticat_user_ty_c1ae22_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='admin_pppoe_bandwidth',
            field=models.CharField(default='100M', help_text='Bandwidth limit for admin PPPoE', max_length=20),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='admin_pppoe_priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='high', help_text='QoS priority for admin PPPoE connections', max_length=20),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='connection_type',
            field=models.CharField(choices=[('hotspot', 'Hotspot'), ('pppoe', 'PPPoE'), ('admin', 'Admin Portal'), ('mixed', 'Mixed Access')], db_index=True, default='hotspot', max_length=20),
        ),
        migrations.AddIndex(
            model_name='useraccount',
            index=models.Index(fields=['user_type', 'pppoe_username'], name='authenticat_user_ty_f3f2f8_idx'),
        ),
        migrations.AddIndex(
            model_name='useraccount',
            index=models.Index(fields=['admin_pppoe_priority'], name='authenticat_admin_p_2e2a3e_idx'),
        ),
    ]
