// // src/components/PaymentConfiguration/SimpleMpesaConfig.jsx
// import React from 'react';
// import { FiInfo } from 'react-icons/fi';

// const SimpleMpesaConfig = ({ method, theme }) => {
//   return (
//     <div className={`p-4 rounded-lg ${theme === 'dark' ? 'bg-gray-700/30' : 'bg-blue-50'} mb-6`}>
//       <div className="flex items-center mb-3">
//         <FiInfo className={`mr-2 ${theme === 'dark' ? 'text-blue-400' : 'text-blue-600'}`} />
//         <span className={`text-sm ${theme === 'dark' ? 'text-blue-300' : 'text-blue-700'}`}>
//           M-Pesa uses automatic callback handling. Webhook secret is auto-generated by the system.
//         </span>
//       </div>
      
//       {method.callbackURL && (
//         <div className="mt-2">
//           <label className={`block text-sm font-medium ${theme === 'dark' ? 'text-gray-300' : 'text-gray-700'}`}>
//             Callback URL
//           </label>
//           <div className={`mt-1 p-2 rounded border ${theme === 'dark' ? 'bg-gray-600 border-gray-500' : 'bg-gray-100 border-gray-300'}`}>
//             <code className="text-sm break-all">{method.callbackURL}</code>
//           </div>
//           <p className={`mt-1 text-xs ${theme === 'dark' ? 'text-gray-400' : 'text-gray-500'}`}>
//             This URL receives M-Pesa payment notifications automatically
//           </p>
//         </div>
//       )}
//     </div>
//   );
// };

// export default SimpleMpesaConfig;







// src/components/PaymentConfiguration/SimpleMpesaConfig.jsx
import React from 'react';
import { FiInfo, FiCheckCircle } from 'react-icons/fi';

const SimpleMpesaConfig = ({ method, theme }) => {
  const cardClass = theme === 'dark'
    ? 'bg-gray-800/50 border border-gray-600'
    : 'bg-blue-50 border border-blue-200';

  const titleClass = theme === 'dark' ? 'text-blue-300' : 'text-blue-700';
  const textClass = theme === 'dark' ? 'text-blue-200' : 'text-blue-600';
  const listClass = theme === 'dark' ? 'text-gray-300' : 'text-gray-700';

  return (
    <div className={`p-4 rounded-lg ${cardClass} mb-6`}>
      <div className="flex items-start mb-3">
        <FiInfo className={`mt-1 mr-2 flex-shrink-0 ${titleClass}`} />
        <div>
          <h4 className={`font-medium ${titleClass}`}>
            M-Pesa Automatic Configuration
          </h4>
          <p className={`text-sm mt-1 ${textClass}`}>
            M-Pesa uses automatic callback handling. Webhook secret is auto-generated by the system.
          </p>
        </div>
      </div>
      
      <div className="ml-6 space-y-2">
        <div className="flex items-center">
          <FiCheckCircle className={`h-4 w-4 mr-2 ${theme === 'dark' ? 'text-green-400' : 'text-green-600'}`} />
          <span className={`text-sm ${listClass}`}>Automatic STK Push processing</span>
        </div>
        <div className="flex items-center">
          <FiCheckCircle className={`h-4 w-4 mr-2 ${theme === 'dark' ? 'text-green-400' : 'text-green-600'}`} />
          <span className={`text-sm ${listClass}`}>Real-time payment notifications</span>
        </div>
        <div className="flex items-center">
          <FiCheckCircle className={`h-4 w-4 mr-2 ${theme === 'dark' ? 'text-green-400' : 'text-green-600'}`} />
          <span className={`text-sm ${listClass}`}>Secure webhook validation</span>
        </div>
      </div>
      
      {method.callbackURL && (
        <div className="mt-3 p-3 rounded border bg-opacity-20 bg-white">
          <label className={`block text-sm font-medium ${theme === 'dark' ? 'text-gray-300' : 'text-gray-700'}`}>
            Callback URL
          </label>
          <div className={`mt-1 p-2 rounded border ${theme === 'dark' ? 'bg-gray-600 border-gray-500' : 'bg-gray-100 border-gray-300'}`}>
            <code className="text-sm break-all font-mono">{method.callbackURL}</code>
          </div>
          <p className={`mt-1 text-xs ${theme === 'dark' ? 'text-gray-400' : 'text-gray-500'}`}>
            This URL receives M-Pesa payment notifications automatically
          </p>
        </div>
      )}
    </div>
  );
};

export default SimpleMpesaConfig;