FROM python:3.10-bullseye

# Environment variables
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV DJANGO_SETTINGS_MODULE=interlink.settings

# Set working directory
WORKDIR /app/backend

# Install system dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
    gcc \
    libmariadb-dev \
    python3-dev \
    libffi-dev \
    pkg-config \
    # Pillow dependencies
    libjpeg-dev \
    zlib1g-dev \
    libpng-dev \
    libfreetype6-dev \
    liblcms2-dev \
    libopenjp2-7-dev \
    libtiff-dev \
    libwebp-dev \
    # Additional dependencies
    libxml2-dev \
    libxslt-dev \
    libpq-dev \
    bash \
    curl \
    && rm -rf /var/lib/apt/lists/*

# Upgrade pip
RUN pip install --upgrade pip

# Install app dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt --no-build-isolation --jobs=1

# Install dev-only tools
RUN pip install debugpy

# Copy entrypoint script
COPY entrypoint.sh .
RUN chmod +x entrypoint.sh

# Copy source code
COPY . /app/backend

# Expose port
EXPOSE 8000

# Run development entrypoint
ENTRYPOINT ["./entrypoint.sh"]
