# Generated by Django 5.1.3 on 2025-01-28 14:25

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("validity", models.CharField(max_length=20)),
                ("data", models.CharField(max_length=20)),
                ("price", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=20)),
                ("last_login", models.DateTimeField(default=django.utils.timezone.now)),
                ("active", models.BooleanField(default=True)),
                ("data_used", models.FloatField(default=0)),
                ("data_total", models.FloatField(default=100)),
                ("data_unit", models.CharField(default="GB", max_length=10)),
                (
                    "payment_status",
                    models.CharField(
                        choices=[("Paid", "Paid"), ("Pending", "Pending")],
                        default="Pending",
                        max_length=20,
                    ),
                ),
                (
                    "subscription_plan",
                    models.CharField(
                        choices=[
                            ("Premium", "Premium"),
                            ("Plus", "Plus"),
                            ("Basic", "Basic"),
                        ],
                        default="Basic",
                        max_length=20,
                    ),
                ),
                ("subscription_start_date", models.DateField()),
                ("subscription_expiry_date", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="UserBilling",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone_number", models.CharField(max_length=20)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user_management.userprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("login", "Login"),
                            ("logout", "Logout"),
                            ("data_usage", "Data Usage"),
                            ("payment_success", "Payment Success"),
                            ("payment_failed", "Payment Failed"),
                        ],
                        max_length=20,
                    ),
                ),
                ("details", models.TextField()),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="user_management.userprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
                ("amount", models.FloatField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Paid", "Paid"),
                            ("Failed", "Failed"),
                            ("Pending", "Pending"),
                        ],
                        default="Pending",
                        max_length=20,
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="user_management.plan",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user_management.userprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserPlan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "assigned_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("device_mac_address", models.CharField(max_length=17)),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Completed", "Completed"),
                            ("Failed", "Failed"),
                        ],
                        default="Pending",
                        max_length=20,
                    ),
                ),
                ("transaction_id", models.CharField(max_length=50, unique=True)),
                (
                    "plan",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="user_management.plan",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user_management.userprofile",
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "device_mac_address")},
            },
        ),
    ]
