# Generated by Django 5.1.3 on 2025-04-28 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("account", "0002_alter_activitylog_options_alter_client_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BrowsingHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField()),
                ("frequency", models.CharField(max_length=20)),
                ("data_used", models.CharField(max_length=20)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="browsing_history",
                        to="account.client",
                    ),
                ),
            ],
            options={
                "verbose_name": "Browsing History",
                "verbose_name_plural": "Browsing Histories",
                "ordering": ["-timestamp"],
            },
        ),
    ]
