# Generated by Django 5.2.3 on 2025-11-11 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network_management', '0005_remove_router_hotspot_config_and_more'),
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='browsinghistory',
            name='pppoe_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='browsing_history', to='network_management.pppoeuser'),
        ),
        migrations.AddField(
            model_name='communicationlog',
            name='connection_type',
            field=models.CharField(choices=[('hotspot', 'Hotspot'), ('pppoe', 'PPPoE')], default='hotspot', max_length=10),
        ),
        migrations.AlterField(
            model_name='communicationlog',
            name='trigger_type',
            field=models.CharField(choices=[('data_usage', 'Data Usage Alert'), ('plan_expiry', 'Plan Expiry Warning'), ('payment', 'Payment Confirmation'), ('manual', 'Manual Send'), ('system', 'System Alert'), ('router_disconnect', 'Router Disconnected'), ('hotspot_limit_reached', 'Hotspot Data Limit Reached'), ('pppoe_limit_reached', 'PPPoE Data Limit Reached')], default='manual', max_length=30),
        ),
    ]
