# Generated by Django 5.1.3 on 2025-01-29 13:03

import django.utils.timezone
import phonenumber_field.modelfields
import user_management.models.user_profile
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_management", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                max_length=128, region=None, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="subscription_expiry_date",
            field=models.DateField(
                default=user_management.models.user_profile.UserProfile.calculate_expiry_date
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="subscription_start_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
