# Generated by Django 5.2.3 on 2025-09-09 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network_management', '0001_initial'),
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='browsinghistory',
            name='data_used',
        ),
        migrations.AddField(
            model_name='browsinghistory',
            name='hotspot_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='browsing_history', to='network_management.hotspotuser'),
        ),
        migrations.AddField(
            model_name='browsinghistory',
            name='router',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='browsing_history', to='network_management.router'),
        ),
        migrations.AddField(
            model_name='communicationlog',
            name='router',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communication_logs', to='network_management.router'),
        ),
        migrations.AlterField(
            model_name='communicationlog',
            name='trigger_type',
            field=models.CharField(choices=[('data_usage', 'Data Usage Alert'), ('plan_expiry', 'Plan Expiry Warning'), ('payment', 'Payment Confirmation'), ('manual', 'Manual Send'), ('system', 'System Alert'), ('router_disconnect', 'Router Disconnected'), ('hotspot_limit_reached', 'Hotspot Data Limit Reached')], default='manual', max_length=30),
        ),
    ]
