# Generated by Django 5.2.3 on 2025-09-10 10:02

import django.utils.timezone
import user_management.models.bulk_actions_model
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0002_remove_browsinghistory_data_used_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('import', 'User Import'), ('message', 'Bulk Message'), ('activate', 'Activate Users'), ('deactivate', 'Deactivate Users'), ('change_plan', 'Change Plan'), ('delete', 'Delete Users')], max_length=20)),
                ('message_type', models.CharField(blank=True, max_length=20)),
                ('total_users', models.PositiveIntegerField()),
                ('success_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('partial', 'Partial Success'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('errors', models.JSONField(default=list)),
                ('scheduled_for', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('message', models.TextField(max_length=160)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SMSAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_messages', models.PositiveIntegerField(default=0)),
                ('successful_messages', models.PositiveIntegerField(default=0)),
                ('failed_messages', models.PositiveIntegerField(default=0)),
                ('active_triggers', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'SMS Analytics',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='SMSAutomationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('sms_gateway', models.CharField(choices=[('africas_talking', "Africa's Talking"), ('twilio', 'Twilio'), ('smpp', 'SMPP'), ('nexmo', 'Vonage (Nexmo)')], default='africas_talking', max_length=20)),
                ('api_key', models.CharField(blank=True, max_length=200)),
                ('username', models.CharField(blank=True, max_length=100)),
                ('sender_id', models.CharField(blank=True, max_length=50)),
                ('send_time_start', models.TimeField(default='08:00')),
                ('send_time_end', models.TimeField(default='20:00')),
                ('max_messages_per_day', models.PositiveIntegerField(default=1000)),
                ('low_balance_alert', models.BooleanField(default=True)),
                ('balance_threshold', models.PositiveIntegerField(default=100)),
                ('sms_balance', models.PositiveIntegerField(default=1000)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'SMS Automation Settings',
            },
        ),
        migrations.CreateModel(
            name='SMSTrigger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('trigger_type', models.CharField(choices=[('data_usage', 'Data Usage'), ('plan_expiry', 'Plan Expiry'), ('onboarding', 'Onboarding')], max_length=20)),
                ('threshold', models.PositiveIntegerField(blank=True, null=True)),
                ('days_before', models.PositiveIntegerField(blank=True, null=True)),
                ('event', models.CharField(blank=True, choices=[('signup', 'After Signup'), ('first_payment', 'After First Payment'), ('plan_activation', 'After Plan Activation')], max_length=20, null=True)),
                ('message', models.TextField(max_length=160)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_triggered', models.DateTimeField(blank=True, null=True)),
                ('sent_count', models.PositiveIntegerField(default=0)),
                ('success_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserImportFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=user_management.models.bulk_actions_model.user_import_file_path)),
                ('original_filename', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processed', models.BooleanField(default=False)),
            ],
        ),
    ]
