# Generated by Django 5.2.3 on 2025-11-14 13:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_initial_mysql_fix'),
        ('user_management', '0002_browsinghistory_pppoe_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='smstrigger',
            options={'ordering': ['-created_at'], 'verbose_name': 'SMS Trigger', 'verbose_name_plural': 'SMS Triggers'},
        ),
        migrations.AddField(
            model_name='browsinghistory',
            name='data_used_bytes',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='communicationlog',
            name='delivery_confirmations',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='browsinghistory',
            name='frequency',
            field=models.CharField(default='Once', max_length=20),
        ),
        migrations.AlterField(
            model_name='browsinghistory',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='browsinghistory',
            name='url',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='communicationlog',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='communicationlog',
            name='trigger_type',
            field=models.CharField(choices=[('data_usage', 'Data Usage Alert'), ('plan_expiry', 'Plan Expiry Warning'), ('payment', 'Payment Confirmation'), ('manual', 'Manual Send'), ('system', 'System Alert'), ('router_disconnect', 'Router Disconnected'), ('hotspot_limit_reached', 'Hotspot Data Limit Reached'), ('pppoe_limit_reached', 'PPPoE Data Limit Reached'), ('onboarding', 'Onboarding Message'), ('test', 'Test Message')], default='manual', max_length=30),
        ),
        migrations.AlterField(
            model_name='smstrigger',
            name='days_before',
            field=models.PositiveIntegerField(blank=True, help_text='Days before plan expiry', null=True),
        ),
        migrations.AlterField(
            model_name='smstrigger',
            name='threshold',
            field=models.PositiveIntegerField(blank=True, help_text='Percentage for data usage alerts', null=True),
        ),
        migrations.AlterField(
            model_name='smstrigger',
            name='trigger_type',
            field=models.CharField(choices=[('data_usage', 'Data Usage Alert'), ('plan_expiry', 'Plan Expiry Warning'), ('onboarding', 'Onboarding Message'), ('payment', 'Payment Confirmation'), ('system', 'System Notification')], max_length=20),
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(limit_choices_to={'user_type': 'client'}, on_delete=django.db.models.deletion.CASCADE, related_name='subscriber_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='browsinghistory',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='browsing_history', to='user_management.client'),
        ),
        migrations.AlterField(
            model_name='communicationlog',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communication_logs', to='user_management.client'),
        ),
        migrations.CreateModel(
            name='ScheduledMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('scheduled_for', models.DateTimeField()),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('sent', 'Sent'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_messages', to='account.client')),
                ('trigger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_messages', to='user_management.smstrigger')),
            ],
            options={
                'ordering': ['scheduled_for'],
            },
        ),
    ]
