# Generated by Django 5.1.3 on 2025-04-29 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_alter_activitylog_options_alter_client_options_and_more"),
        ("user_management", "0002_actionnotification_datausagethreshold_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="actionnotification",
            name="client",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="account.client",
            ),
        ),
        migrations.AlterField(
            model_name="clientanalytics",
            name="payment_status",
            field=models.CharField(
                choices=[("Paid", "Paid"), ("Due", "Due"), ("Expired", "Expired")],
                max_length=20,
            ),
        ),
    ]
