# Generated by Django 5.2.3 on 2025-11-14 14:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0003_alter_smstrigger_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_type', models.CharField(choices=[('general', 'General Note'), ('support', 'Support Ticket'), ('billing', 'Billing Issue'), ('technical', 'Technical Issue'), ('follow_up', 'Follow Up Required')], default='general', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('requires_follow_up', models.BooleanField(default=False)),
                ('follow_up_date', models.DateTimeField(blank=True, null=True)),
                ('follow_up_completed', models.BooleanField(default=False)),
                ('internal_only', models.BooleanField(default=False)),
                ('tags', models.JSONField(blank=True, default=list, help_text='Tags for categorization')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Client Note',
                'verbose_name_plural': 'Client Notes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='browsinghistory',
            name='client',
        ),
        migrations.RemoveField(
            model_name='browsinghistory',
            name='hotspot_user',
        ),
        migrations.RemoveField(
            model_name='browsinghistory',
            name='pppoe_user',
        ),
        migrations.RemoveField(
            model_name='browsinghistory',
            name='router',
        ),
        migrations.RemoveField(
            model_name='communicationlog',
            name='connection_type',
        ),
        migrations.RemoveField(
            model_name='communicationlog',
            name='delivery_confirmations',
        ),
        migrations.RemoveField(
            model_name='communicationlog',
            name='router',
        ),
        migrations.AddField(
            model_name='client',
            name='acquisition_source',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='communication_preferences',
            field=models.JSONField(default=dict, help_text='Client communication preferences and settings'),
        ),
        migrations.AddField(
            model_name='client',
            name='customer_since',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='client',
            name='last_contact',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='loyalty_tier',
            field=models.CharField(choices=[('new', 'New'), ('regular', 'Regular'), ('premium', 'Premium'), ('vip', 'VIP')], default='new', max_length=20),
        ),
        migrations.AddField(
            model_name='client',
            name='notes',
            field=models.TextField(blank=True, help_text='Internal notes about the client', null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='preferred_contact_method',
            field=models.CharField(choices=[('sms', 'SMS'), ('email', 'Email'), ('both', 'Both')], default='sms', max_length=10),
        ),
        migrations.AddField(
            model_name='client',
            name='referral_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='communicationlog',
            name='campaign_id',
            field=models.CharField(blank=True, help_text='Marketing campaign identifier', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='communicationlog',
            name='click_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='communicationlog',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='communicationlog',
            name='engagement_data',
            field=models.JSONField(blank=True, default=dict, help_text='Additional engagement metrics and data'),
        ),
        migrations.AddField(
            model_name='communicationlog',
            name='open_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='communicationlog',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='communicationlog',
            name='response_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='communicationlog',
            name='response_received',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='communicationlog',
            name='response_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='communicationlog',
            name='template_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='communicationlog',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('read', 'Read')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='communicationlog',
            name='trigger_type',
            field=models.CharField(choices=[('marketing', 'Marketing Campaign'), ('support', 'Support Response'), ('billing', 'Billing Notification'), ('manual', 'Manual Send'), ('onboarding', 'Onboarding Message'), ('retention', 'Retention Campaign')], default='manual', max_length=30),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['loyalty_tier'], name='user_manage_loyalty_39175f_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['customer_since'], name='user_manage_custome_dc523a_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['preferred_contact_method'], name='user_manage_preferr_7d8ef5_idx'),
        ),
        migrations.AddIndex(
            model_name='communicationlog',
            index=models.Index(fields=['client', 'timestamp'], name='user_manage_client__485d57_idx'),
        ),
        migrations.AddIndex(
            model_name='communicationlog',
            index=models.Index(fields=['message_type', 'status'], name='user_manage_message_d28dd8_idx'),
        ),
        migrations.AddIndex(
            model_name='communicationlog',
            index=models.Index(fields=['campaign_id'], name='user_manage_campaig_6d179e_idx'),
        ),
        migrations.AddField(
            model_name='clientnote',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_notes', to='user_management.client'),
        ),
        migrations.AddField(
            model_name='clientnote',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_notes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='BrowsingHistory',
        ),
        migrations.AddIndex(
            model_name='clientnote',
            index=models.Index(fields=['client', 'note_type'], name='user_manage_client__80a993_idx'),
        ),
        migrations.AddIndex(
            model_name='clientnote',
            index=models.Index(fields=['requires_follow_up', 'follow_up_date'], name='user_manage_require_1208b8_idx'),
        ),
        migrations.AddIndex(
            model_name='clientnote',
            index=models.Index(fields=['priority'], name='user_manage_priorit_cfda9b_idx'),
        ),
    ]
