# Generated by Django 5.1.3 on 2025-04-30 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_alter_activitylog_options_alter_client_options_and_more"),
        ("user_management", "0003_actionnotification_client_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="actionnotification",
            name="client",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="action_notifications",
                to="account.client",
            ),
        ),
        migrations.AddIndex(
            model_name="actionnotification",
            index=models.Index(
                fields=["client", "is_read"], name="user_manage_client__0ac0f8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="actionnotification",
            index=models.Index(
                fields=["type", "created_at"], name="user_manage_type_9e3dc5_idx"
            ),
        ),
    ]
