# Generated by Django 5.2.3 on 2025-11-18 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0004_clientnote_remove_browsinghistory_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communicationlog',
            name='engagement_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
