# Generated by Django 5.1.3 on 2025-04-04 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("otp_auth", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="otp",
            options={"verbose_name": "OTP Code", "verbose_name_plural": "OTP Codes"},
        ),
        migrations.AddField(
            model_name="otp",
            name="attempts",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="otp",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name="otp",
            index=models.Index(
                fields=["phone_number", "created_at"],
                name="otp_auth_ot_phone_n_74ed32_idx",
            ),
        ),
    ]
