# Generated by Django 5.1.3 on 2025-04-04 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("otp_auth", "0002_alter_otp_options_otp_attempts_otp_is_verified_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="otp",
            options={},
        ),
        migrations.RemoveIndex(
            model_name="otp",
            name="otp_auth_ot_phone_n_74ed32_idx",
        ),
        migrations.RenameField(
            model_name="otp",
            old_name="otp_code",
            new_name="otp",
        ),
        migrations.AlterField(
            model_name="otp",
            name="attempts",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="otp",
            name="phone_number",
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
