# Generated by Django 5.1.3 on 2025-04-04 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("otp_auth", "0003_alter_otp_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="otp",
            old_name="otp",
            new_name="otp_code",
        ),
        migrations.AddIndex(
            model_name="otp",
            index=models.Index(
                fields=["phone_number"], name="otp_auth_ot_phone_n_7ad0a9_idx"
            ),
        ),
    ]
