# Generated by Django 5.2.3 on 2026-01-22 14:41

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connection_status', models.CharField(choices=[('offline', 'Offline'), ('suspended', 'Suspended'), ('expired', 'Expired')], db_index=True, default='offline', max_length=20)),
                ('last_connection', models.DateTimeField(blank=True, null=True)),
                ('total_connection_time', models.DurationField(default=datetime.timedelta)),
                ('data_used', models.BigIntegerField(default=0)),
                ('data_capacity', models.BigIntegerField(default=0)),
                ('pppoe_service_name', models.CharField(blank=True, max_length=100, null=True)),
                ('pppoe_local_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('pppoe_remote_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('hotspot_mac_address', models.CharField(blank=True, max_length=17, null=True)),
                ('hotspot_session_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(limit_choices_to={'user_type': 'client'}, on_delete=django.db.models.deletion.CASCADE, related_name='client_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('access', 'Data Access'), ('modify', 'Data Modification'), ('delete', 'Data Deletion'), ('signup', 'New Client Signup'), ('outage', 'Network Outage'), ('payment', 'Payment Event'), ('login', 'Login'), ('logout', 'Logout'), ('system_alert', 'System Alert'), ('pppoe_connect', 'PPPoE Connection'), ('pppoe_disconnect', 'PPPoE Disconnection'), ('hotspot_connect', 'Hotspot Connection'), ('hotspot_disconnect', 'Hotspot Disconnection'), ('data_usage', 'Data Usage Update'), ('plan_change', 'Plan Change')], max_length=50)),
                ('description', models.TextField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_critical', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('related_user', models.ForeignKey(blank=True, help_text='Affected user', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_activity_logs', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
                ('related_client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to='account.client')),
            ],
            options={
                'verbose_name': 'Activity Log',
                'verbose_name_plural': 'Activity Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='HotspotSessionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_start', models.DateTimeField(default=django.utils.timezone.now)),
                ('session_end', models.DateTimeField(blank=True, null=True)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('mac_address', models.CharField(max_length=17)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('data_used', models.BigIntegerField(default=0)),
                ('router_identifier', models.CharField(blank=True, max_length=100, null=True)),
                ('session_id', models.CharField(blank=True, max_length=100, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotspot_session_logs', to='account.client')),
            ],
            options={
                'ordering': ['-session_start'],
            },
        ),
        migrations.CreateModel(
            name='LoginHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('ip_address', models.GenericIPAddressField()),
                ('device', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('user_agent', models.TextField(blank=True)),
                ('login_type', models.CharField(choices=[('dashboard', 'Dashboard'), ('hotspot', 'Hotspot'), ('pppoe', 'PPPoE')], default='dashboard', max_length=20)),
                ('is_suspicious', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('system', 'System Notification'), ('billing', 'Billing Notification'), ('usage', 'Usage Alert'), ('security', 'Security Alert'), ('maintenance', 'Maintenance Notification'), ('pppoe', 'PPPoE Status'), ('hotspot', 'Hotspot Status')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('read', models.BooleanField(default=False)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='low', max_length=10)),
                ('related_id', models.UUIDField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('related_client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='account.client')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='PPPoEConnectionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_start', models.DateTimeField(default=django.utils.timezone.now)),
                ('session_end', models.DateTimeField(blank=True, null=True)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('local_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('remote_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('data_sent', models.BigIntegerField(default=0)),
                ('data_received', models.BigIntegerField(default=0)),
                ('termination_reason', models.CharField(blank=True, max_length=100, null=True)),
                ('router_identifier', models.CharField(blank=True, max_length=100, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pppoe_connection_logs', to='account.client')),
            ],
            options={
                'ordering': ['-session_start'],
            },
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['user', 'created_at'], name='account_cli_user_id_bffa23_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['connection_status', 'created_at'], name='account_cli_connect_dc6293_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['last_connection'], name='account_cli_last_co_f259d2_idx'),
        ),
        migrations.AddConstraint(
            model_name='client',
            constraint=models.UniqueConstraint(fields=('user',), name='unique_client_user'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['action_type', 'timestamp', 'is_critical'], name='account_act_action__48e9d3_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['user', 'timestamp'], name='account_act_user_id_7175ef_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['related_client', 'timestamp'], name='account_act_related_a41184_idx'),
        ),
        migrations.AddIndex(
            model_name='hotspotsessionlog',
            index=models.Index(fields=['client', 'session_start'], name='account_hot_client__5750ef_idx'),
        ),
        migrations.AddIndex(
            model_name='hotspotsessionlog',
            index=models.Index(fields=['mac_address', 'session_start'], name='account_hot_mac_add_8484a8_idx'),
        ),
        migrations.AddIndex(
            model_name='loginhistory',
            index=models.Index(fields=['user', 'timestamp', 'login_type'], name='account_log_user_id_f6ca27_idx'),
        ),
        migrations.AddIndex(
            model_name='loginhistory',
            index=models.Index(fields=['is_suspicious', 'timestamp'], name='account_log_is_susp_5fd0c1_idx'),
        ),
        migrations.AddIndex(
            model_name='loginhistory',
            index=models.Index(fields=['login_type', 'timestamp'], name='account_log_login_t_d4f7fb_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'read', 'timestamp', 'priority'], name='account_not_user_id_6043db_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['type', 'timestamp'], name='account_not_type_85b650_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['related_client', 'timestamp'], name='account_not_related_d7b3d4_idx'),
        ),
        migrations.AddIndex(
            model_name='pppoeconnectionlog',
            index=models.Index(fields=['client', 'session_start'], name='account_ppp_client__acfcc6_idx'),
        ),
        migrations.AddIndex(
            model_name='pppoeconnectionlog',
            index=models.Index(fields=['session_start', 'session_end'], name='account_ppp_session_b2bb71_idx'),
        ),
    ]
