# Generated by Django 5.2.3 on 2025-09-19 10:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['-created_at'], 'verbose_name': 'Client', 'verbose_name_plural': 'Clients'},
        ),
        migrations.RemoveIndex(
            model_name='activitylog',
            name='account_act_action__a98223_idx',
        ),
        migrations.RemoveIndex(
            model_name='activitylog',
            name='account_act_related_020d49_idx',
        ),
        migrations.RemoveIndex(
            model_name='activitylog',
            name='account_act_is_crit_065bd9_idx',
        ),
        migrations.RemoveIndex(
            model_name='client',
            name='account_cli_user_id_53efdc_idx',
        ),
        migrations.RemoveIndex(
            model_name='loginhistory',
            name='account_log_user_id_0084d7_idx',
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='account_not_user_id_1590fb_idx',
        ),
        migrations.AddField(
            model_name='activitylog',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='client',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='loginhistory',
            name='is_suspicious',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='related_user',
            field=models.ForeignKey(blank=True, help_text='Affected user', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_activity_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='loginhistory',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='notification',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['action_type', 'timestamp', 'is_critical'], name='account_act_action__48e9d3_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['user', 'related_user'], name='account_act_user_id_8b3f7d_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['user', 'created_at'], name='account_cli_user_id_bffa23_idx'),
        ),
        migrations.AddIndex(
            model_name='loginhistory',
            index=models.Index(fields=['user', 'timestamp', 'ip_address'], name='account_log_user_id_54dbfa_idx'),
        ),
        migrations.AddIndex(
            model_name='loginhistory',
            index=models.Index(fields=['is_suspicious'], name='account_log_is_susp_2b6580_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'read', 'timestamp', 'priority'], name='account_not_user_id_6043db_idx'),
        ),
        migrations.AddConstraint(
            model_name='client',
            constraint=models.UniqueConstraint(fields=('user',), name='unique_client_user'),
        ),
    ]
