# Generated by Django 5.1.3 on 2025-04-27 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
        ("internet_plans", "0001_initial"),
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="activitylog",
            options={
                "ordering": ["-timestamp"],
                "verbose_name": "Activity Log",
                "verbose_name_plural": "Activity Logs",
            },
        ),
        migrations.AlterModelOptions(
            name="client",
            options={"verbose_name": "Client", "verbose_name_plural": "Clients"},
        ),
        migrations.AlterModelOptions(
            name="payment",
            options={
                "ordering": ["-timestamp"],
                "verbose_name": "Payment",
                "verbose_name_plural": "Payments",
            },
        ),
        migrations.AlterModelOptions(
            name="router",
            options={
                "ordering": ["name"],
                "verbose_name": "Router",
                "verbose_name_plural": "Routers",
            },
        ),
        migrations.AlterModelOptions(
            name="subscription",
            options={
                "ordering": ["-start_date"],
                "verbose_name": "Subscription",
                "verbose_name_plural": "Subscriptions",
            },
        ),
        migrations.AddField(
            model_name="payment",
            name="subscription",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payments",
                to="account.subscription",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="transaction",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payments",
                to="payments.transaction",
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="internet_plan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="subscriptions",
                to="internet_plans.internetplan",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="account.client",
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subscriptions",
                to="account.client",
            ),
        ),
        migrations.AddIndex(
            model_name="client",
            index=models.Index(
                fields=["phonenumber"], name="account_cli_phonenu_be3055_idx"
            ),
        ),
    ]
