# Generated by Django 5.2.3 on 2025-11-28 12:51

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_initial_mysql_fix'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HotspotSessionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_start', models.DateTimeField(default=django.utils.timezone.now)),
                ('session_end', models.DateTimeField(blank=True, null=True)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('mac_address', models.CharField(max_length=17)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('data_used', models.BigIntegerField(default=0)),
                ('router_identifier', models.CharField(blank=True, max_length=100, null=True)),
                ('session_id', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'ordering': ['-session_start'],
            },
        ),
        migrations.CreateModel(
            name='PPPoEConnectionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_start', models.DateTimeField(default=django.utils.timezone.now)),
                ('session_end', models.DateTimeField(blank=True, null=True)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('local_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('remote_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('data_sent', models.BigIntegerField(default=0)),
                ('data_received', models.BigIntegerField(default=0)),
                ('termination_reason', models.CharField(blank=True, max_length=100, null=True)),
                ('router_identifier', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'ordering': ['-session_start'],
            },
        ),
        migrations.RemoveIndex(
            model_name='activitylog',
            name='account_act_user_id_8b3f7d_idx',
        ),
        migrations.RemoveIndex(
            model_name='loginhistory',
            name='account_log_user_id_54dbfa_idx',
        ),
        migrations.RemoveIndex(
            model_name='loginhistory',
            name='account_log_is_susp_2b6580_idx',
        ),
        migrations.AddField(
            model_name='activitylog',
            name='related_client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to='account.client'),
        ),
        migrations.AddField(
            model_name='client',
            name='connection_status',
            field=models.CharField(choices=[('offline', 'Offline'), ('suspended', 'Suspended'), ('expired', 'Expired')], db_index=True, default='offline', max_length=20),
        ),
        migrations.AddField(
            model_name='client',
            name='data_capacity',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='client',
            name='data_used',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='client',
            name='hotspot_mac_address',
            field=models.CharField(blank=True, max_length=17, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='hotspot_session_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='last_connection',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='client',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='pppoe_local_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='pppoe_remote_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='pppoe_service_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='total_connection_time',
            field=models.DurationField(default=datetime.timedelta),
        ),
        migrations.AddField(
            model_name='loginhistory',
            name='login_type',
            field=models.CharField(choices=[('dashboard', 'Dashboard'), ('hotspot', 'Hotspot'), ('pppoe', 'PPPoE')], default='dashboard', max_length=20),
        ),
        migrations.AddField(
            model_name='notification',
            name='related_client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='account.client'),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='action_type',
            field=models.CharField(choices=[('access', 'Data Access'), ('modify', 'Data Modification'), ('delete', 'Data Deletion'), ('signup', 'New Client Signup'), ('outage', 'Network Outage'), ('payment', 'Payment Event'), ('login', 'Login'), ('logout', 'Logout'), ('system_alert', 'System Alert'), ('pppoe_connect', 'PPPoE Connection'), ('pppoe_disconnect', 'PPPoE Disconnection'), ('hotspot_connect', 'Hotspot Connection'), ('hotspot_disconnect', 'Hotspot Disconnection'), ('data_usage', 'Data Usage Update'), ('plan_change', 'Plan Change')], max_length=50),
        ),
        migrations.AlterField(
            model_name='notification',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='low', max_length=10),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('system', 'System Notification'), ('billing', 'Billing Notification'), ('usage', 'Usage Alert'), ('security', 'Security Alert'), ('maintenance', 'Maintenance Notification'), ('pppoe', 'PPPoE Status'), ('hotspot', 'Hotspot Status')], max_length=50),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['user', 'timestamp'], name='account_act_user_id_7175ef_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['related_client', 'timestamp'], name='account_act_related_a41184_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['connection_status', 'created_at'], name='account_cli_connect_dc6293_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['last_connection'], name='account_cli_last_co_f259d2_idx'),
        ),
        migrations.AddIndex(
            model_name='loginhistory',
            index=models.Index(fields=['user', 'timestamp', 'login_type'], name='account_log_user_id_f6ca27_idx'),
        ),
        migrations.AddIndex(
            model_name='loginhistory',
            index=models.Index(fields=['is_suspicious', 'timestamp'], name='account_log_is_susp_5fd0c1_idx'),
        ),
        migrations.AddIndex(
            model_name='loginhistory',
            index=models.Index(fields=['login_type', 'timestamp'], name='account_log_login_t_d4f7fb_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['type', 'timestamp'], name='account_not_type_85b650_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['related_client', 'timestamp'], name='account_not_related_d7b3d4_idx'),
        ),
        migrations.AddField(
            model_name='hotspotsessionlog',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotspot_session_logs', to='account.client'),
        ),
        migrations.AddField(
            model_name='pppoeconnectionlog',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pppoe_connection_logs', to='account.client'),
        ),
        migrations.AddIndex(
            model_name='hotspotsessionlog',
            index=models.Index(fields=['client', 'session_start'], name='account_hot_client__5750ef_idx'),
        ),
        migrations.AddIndex(
            model_name='hotspotsessionlog',
            index=models.Index(fields=['mac_address', 'session_start'], name='account_hot_mac_add_8484a8_idx'),
        ),
        migrations.AddIndex(
            model_name='pppoeconnectionlog',
            index=models.Index(fields=['client', 'session_start'], name='account_ppp_client__acfcc6_idx'),
        ),
        migrations.AddIndex(
            model_name='pppoeconnectionlog',
            index=models.Index(fields=['session_start', 'session_end'], name='account_ppp_session_b2bb71_idx'),
        ),
    ]
