# Generated by Django 5.1.3 on 2025-03-23 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FinancialData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "month",
                    models.CharField(
                        help_text="Month of financial record.", max_length=10
                    ),
                ),
                (
                    "income",
                    models.DecimalField(
                        decimal_places=2, help_text="Total income.", max_digits=10
                    ),
                ),
                (
                    "profit",
                    models.DecimalField(
                        decimal_places=2, help_text="Net profit.", max_digits=10
                    ),
                ),
                (
                    "expenses",
                    models.DecimalField(
                        decimal_places=2, help_text="Total expenses.", max_digits=10
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GridItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="Descriptive name of the grid item.", max_length=100
                    ),
                ),
                (
                    "value",
                    models.CharField(
                        help_text="Displayed numeric or currency value.", max_length=20
                    ),
                ),
                (
                    "rate",
                    models.FloatField(help_text="Percentage change for the item."),
                ),
                (
                    "icon",
                    models.CharField(
                        help_text="Name of the associated icon file.", max_length=100
                    ),
                ),
                (
                    "signal_icon",
                    models.CharField(
                        blank=True,
                        help_text="Optional secondary icon.",
                        max_length=100,
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Grid Items",
            },
        ),
        migrations.CreateModel(
            name="RevenueData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "month",
                    models.CharField(
                        help_text="Month for which revenue is recorded.", max_length=10
                    ),
                ),
                (
                    "targeted_revenue",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Planned revenue target.",
                        max_digits=10,
                    ),
                ),
                (
                    "projected_revenue",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Actual projected revenue.",
                        max_digits=10,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SalesData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "plan",
                    models.CharField(
                        choices=[
                            ("basic", "Basic Plan"),
                            ("plus", "Plus Plan"),
                            ("premium", "Premium Plan"),
                        ],
                        help_text="Type of internet plan sold.",
                        max_length=10,
                    ),
                ),
                (
                    "month",
                    models.CharField(
                        help_text="Month of recorded sales.", max_length=10
                    ),
                ),
                (
                    "sales",
                    models.PositiveIntegerField(help_text="Number of sales recorded."),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VisitorAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "plan",
                    models.CharField(
                        choices=[
                            ("basic", "Basic Plan"),
                            ("plus", "Plus Plan"),
                            ("premium", "Premium Plan"),
                        ],
                        help_text="Type of internet plan.",
                        max_length=10,
                    ),
                ),
                (
                    "visitors",
                    models.PositiveIntegerField(help_text="Number of unique visitors."),
                ),
            ],
        ),
    ]
