# Generated by Django 5.1.3 on 2025-01-30 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FinancialData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "month",
                    models.CharField(
                        help_text="Month of financial record (e.g., 'January', 'February').",
                        max_length=10,
                    ),
                ),
                (
                    "income",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total income for the month.",
                        max_digits=10,
                    ),
                ),
                (
                    "profit",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Net profit recorded for the month.",
                        max_digits=10,
                    ),
                ),
                (
                    "expenses",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total expenses incurred during the month.",
                        max_digits=10,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GridItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="Descriptive name of the grid item (e.g., 'Active Users', 'Total Clients').",
                        max_length=100,
                    ),
                ),
                (
                    "value",
                    models.CharField(
                        help_text="Displayed numeric or currency value (e.g., '12', 'KES 10,000').",
                        max_length=20,
                    ),
                ),
                (
                    "rate",
                    models.FloatField(
                        help_text="Percentage change for the item (e.g., 12.5 for 12.5%)."
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        help_text="Name of the associated icon file.", max_length=100
                    ),
                ),
                (
                    "signal_icon",
                    models.CharField(
                        blank=True,
                        help_text="Optional secondary icon, such as a WiFi signal indicator.",
                        max_length=100,
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Grid Items",
            },
        ),
        migrations.CreateModel(
            name="RevenueData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "month",
                    models.CharField(
                        help_text="Month for which revenue is recorded (e.g., 'January', 'February').",
                        max_length=10,
                    ),
                ),
                (
                    "targeted_revenue",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Planned revenue target for the given month.",
                        max_digits=10,
                    ),
                ),
                (
                    "projected_revenue",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Actual projected revenue for the given month.",
                        max_digits=10,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SalesData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "plan",
                    models.CharField(
                        choices=[
                            ("basic", "Basic Plan"),
                            ("plus", "Plus Plan"),
                            ("premium", "Premium Plan"),
                        ],
                        help_text="Type of internet plan sold.",
                        max_length=10,
                    ),
                ),
                (
                    "month",
                    models.CharField(
                        help_text="Month of recorded sales (e.g., 'January', 'February').",
                        max_length=10,
                    ),
                ),
                (
                    "sales",
                    models.PositiveIntegerField(
                        help_text="Number of sales recorded for the selected plan and month."
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VisitorAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "plan",
                    models.CharField(
                        choices=[
                            ("basic", "Basic Plan"),
                            ("plus", "Plus Plan"),
                            ("premium", "Premium Plan"),
                        ],
                        help_text="Type of internet plan associated with the visitor analytics.",
                        max_length=10,
                    ),
                ),
                (
                    "visitors",
                    models.PositiveIntegerField(
                        help_text="Number of unique visitors for the selected plan."
                    ),
                ),
            ],
        ),
    ]
