# Generated by Django 5.2.3 on 2026-01-30 14:38

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeVariantConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(db_index=True, default=False, help_text='Enable time variant controls for this plan')),
                ('start_time', models.TimeField(blank=True, help_text='Start time when plan becomes visible in captive portal (24-hour format)', null=True)),
                ('end_time', models.TimeField(blank=True, help_text='End time when plan disappears from captive portal (24-hour format)', null=True)),
                ('available_days', models.JSONField(blank=True, default=list, help_text="Days of week when plan is available (e.g., ['mon', 'wed', 'fri'])")),
                ('schedule_active', models.BooleanField(default=False, help_text='Enable scheduled availability')),
                ('schedule_start_date', models.DateTimeField(blank=True, help_text='Start date/time for scheduled availability', null=True)),
                ('schedule_end_date', models.DateTimeField(blank=True, help_text='End date/time for scheduled availability', null=True)),
                ('duration_active', models.BooleanField(default=False, help_text='Enable duration-based availability')),
                ('duration_value', models.PositiveIntegerField(default=0, help_text='Duration value (e.g., 7 for 7 days)')),
                ('duration_unit', models.CharField(choices=[('hours', 'Hours'), ('days', 'Days'), ('weeks', 'Weeks'), ('months', 'Months')], default='days', help_text='Duration unit', max_length=10)),
                ('duration_start_date', models.DateTimeField(blank=True, help_text='Start date for duration-based availability', null=True)),
                ('exclusion_dates', models.JSONField(blank=True, default=list, help_text='Specific dates when plan is NOT available (YYYY-MM-DD format)')),
                ('timezone', models.CharField(default='Africa/Nairobi', help_text='Timezone for time calculations (IANA format)', max_length=50)),
                ('force_available', models.BooleanField(default=False, help_text='Override all time restrictions and make plan available')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Time Variant Configuration',
                'verbose_name_plural': 'Time Variant Configurations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlanTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('category', models.CharField(choices=[('Residential', 'Residential'), ('Business', 'Business'), ('Promotional', 'Promotional'), ('Enterprise', 'Enterprise')], db_index=True, default='Residential', max_length=20)),
                ('base_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Base price in KSH', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('access_methods', models.JSONField(default=dict, help_text='Configuration for hotspot and PPPoE access methods')),
                ('is_public', models.BooleanField(db_index=True, default=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('usage_count', models.PositiveIntegerField(db_index=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='Admin who created this template', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_templates', to=settings.AUTH_USER_MODEL)),
                ('time_variant', models.OneToOneField(blank=True, help_text='Time variant configuration for this template', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plan_template', to='internet_plans.timevariantconfig')),
            ],
            options={
                'verbose_name': 'Plan Template',
                'verbose_name_plural': 'Plan Templates',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InternetPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plan_type', models.CharField(choices=[('paid', 'Paid'), ('free_trial', 'Free Trial'), ('promotional', 'Promotional')], db_index=True, default='paid', max_length=20)),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Price in KSH', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('category', models.CharField(choices=[('Residential', 'Residential'), ('Business', 'Business'), ('Promotional', 'Promotional'), ('Enterprise', 'Enterprise')], db_index=True, default='Residential', max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('access_methods', models.JSONField(default=dict, help_text='Configuration for hotspot and PPPoE access methods')),
                ('priority_level', models.IntegerField(choices=[(1, 'Lowest'), (2, 'Low'), (3, 'Medium'), (4, 'High'), (5, 'Highest'), (6, 'Critical'), (7, 'Premium'), (8, 'VIP')], default=4)),
                ('router_specific', models.BooleanField(default=False)),
                ('FUP_policy', models.TextField(blank=True, default='')),
                ('FUP_threshold', models.PositiveIntegerField(default=80, help_text='Usage threshold percentage for FUP', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('purchases', models.PositiveIntegerField(db_index=True, default=0)),
                ('client_sessions', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='Admin who created this plan', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_plans', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(blank=True, help_text='Template used to create this plan', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_plans', to='internet_plans.plantemplate')),
                ('time_variant', models.OneToOneField(blank=True, help_text='Time variant configuration for this plan', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='internet_plan', to='internet_plans.timevariantconfig')),
            ],
            options={
                'verbose_name': 'Internet Plan',
                'verbose_name_plural': 'Internet Plans',
                'ordering': ['-priority_level', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PriceMatrix',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage Discount'), ('fixed', 'Fixed Amount'), ('tiered', 'Tiered Pricing'), ('volume', 'Volume Discount')], default='percentage', max_length=20)),
                ('applies_to', models.CharField(choices=[('plan', 'Specific Plan'), ('category', 'Plan Category'), ('all', 'All Plans')], default='plan', max_length=20)),
                ('target_category', models.CharField(blank=True, max_length=20)),
                ('percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Percentage discount (0-100)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('fixed_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('tier_config', models.JSONField(blank=True, default=list, help_text="Tier configuration: [{'min_qty': 1, 'price': 1000}, ...]")),
                ('min_quantity', models.PositiveIntegerField(default=1)),
                ('max_quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('valid_from', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('valid_to', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('usage_count', models.PositiveIntegerField(default=0)),
                ('total_discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('target_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='price_matrices', to='internet_plans.internetplan')),
            ],
            options={
                'verbose_name': 'Price Matrix',
                'verbose_name_plural': 'Price Matrices',
                'ordering': ['-valid_from', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DiscountRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('rule_type', models.CharField(choices=[('first_time', 'First Time Purchase'), ('loyalty', 'Loyalty Discount'), ('seasonal', 'Seasonal Promotion'), ('referral', 'Referral Bonus'), ('bulk', 'Bulk Purchase')], default='first_time', max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('eligibility_criteria', models.JSONField(blank=True, default=dict, help_text='JSON criteria for eligibility')),
                ('priority', models.PositiveIntegerField(default=1, help_text='Higher priority rules are applied first')),
                ('max_uses_per_client', models.PositiveIntegerField(blank=True, null=True)),
                ('total_usage_limit', models.PositiveIntegerField(blank=True, null=True)),
                ('current_usage', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('price_matrix', models.ForeignKey(help_text='Price matrix to apply', on_delete=django.db.models.deletion.CASCADE, related_name='discount_rules', to='internet_plans.pricematrix')),
            ],
            options={
                'verbose_name': 'Discount Rule',
                'verbose_name_plural': 'Discount Rules',
                'ordering': ['-priority', 'name'],
            },
        ),
        migrations.AddIndex(
            model_name='pricematrix',
            index=models.Index(fields=['applies_to', 'is_active'], name='internet_pl_applies_61271e_idx'),
        ),
        migrations.AddIndex(
            model_name='pricematrix',
            index=models.Index(fields=['valid_from', 'valid_to'], name='internet_pl_valid_f_efc521_idx'),
        ),
        migrations.AddIndex(
            model_name='pricematrix',
            index=models.Index(fields=['target_plan', 'is_active'], name='internet_pl_target__4f604b_idx'),
        ),
        migrations.AddIndex(
            model_name='discountrule',
            index=models.Index(fields=['rule_type', 'is_active'], name='internet_pl_rule_ty_933324_idx'),
        ),
        migrations.AddIndex(
            model_name='discountrule',
            index=models.Index(fields=['priority', 'is_active'], name='internet_pl_priorit_c0041e_idx'),
        ),
        migrations.AddIndex(
            model_name='plantemplate',
            index=models.Index(fields=['name', 'is_active'], name='internet_pl_name_f5bcbb_idx'),
        ),
        migrations.AddIndex(
            model_name='plantemplate',
            index=models.Index(fields=['category', 'is_active'], name='internet_pl_categor_8614ab_idx'),
        ),
        migrations.AddIndex(
            model_name='plantemplate',
            index=models.Index(fields=['is_public', 'is_active'], name='internet_pl_is_publ_cab6d0_idx'),
        ),
        migrations.AddIndex(
            model_name='plantemplate',
            index=models.Index(fields=['created_at'], name='internet_pl_created_e061b6_idx'),
        ),
        migrations.AddIndex(
            model_name='internetplan',
            index=models.Index(fields=['name', 'active'], name='internet_pl_name_f995d6_idx'),
        ),
        migrations.AddIndex(
            model_name='internetplan',
            index=models.Index(fields=['plan_type', 'active'], name='internet_pl_plan_ty_35a64b_idx'),
        ),
        migrations.AddIndex(
            model_name='internetplan',
            index=models.Index(fields=['category', 'active'], name='internet_pl_categor_756e53_idx'),
        ),
        migrations.AddIndex(
            model_name='internetplan',
            index=models.Index(fields=['price'], name='internet_pl_price_e438dc_idx'),
        ),
        migrations.AddIndex(
            model_name='internetplan',
            index=models.Index(fields=['purchases'], name='internet_pl_purchas_60c91a_idx'),
        ),
        migrations.AddIndex(
            model_name='internetplan',
            index=models.Index(fields=['created_at'], name='internet_pl_created_858f34_idx'),
        ),
    ]
