# Generated by Django 5.1.3 on 2025-01-28 14:26

import django.db.models.deletion
import django.utils.timezone
import internet_plans.models.create_plans
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="InternetPlan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Must be unique", max_length=100, unique=True
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "duration",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "data",
                    models.CharField(
                        help_text="Data allowance in GB or 'Unlimited'",
                        max_length=20,
                        validators=[
                            internet_plans.models.create_plans.validate_data_limit
                        ],
                    ),
                ),
                ("description", models.TextField()),
                ("features", models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name="PlanAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("plan_name", models.CharField(max_length=50)),
                ("sales", models.IntegerField()),
                ("active_users", models.IntegerField()),
                ("bandwidth_usage", models.FloatField()),
                ("uptime", models.FloatField()),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name="UserFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("positive", models.IntegerField(default=0)),
                ("neutral", models.IntegerField(default=0)),
                ("negative", models.IntegerField(default=0)),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="internet_plans.plananalytics",
                    ),
                ),
            ],
        ),
    ]
