# Generated by Django 5.1.3 on 2025-03-28 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("internet_plans", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlanAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uptime",
                    models.FloatField(
                        default=99.0, help_text="Percentage uptime (e.g., 99.5)"
                    ),
                ),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics",
                        to="internet_plans.internetplan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Plan Analytic",
                "verbose_name_plural": "Plan Analytics",
            },
        ),
    ]
