# Generated by Django 5.2.3 on 2025-09-19 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('internet_plans', '0001_initial'),
        ('network_management', '0001_initial'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='internetplan',
            name='allowed_routers',
            field=models.ManyToManyField(blank=True, help_text='Routers where this plan can be activated (if router-specific)', to='network_management.router'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='router',
            field=models.ForeignKey(blank=True, help_text='Router where this subscription is active', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='network_management.router'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='payments.transaction'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['router'], name='internet_pl_router__918104_idx'),
        ),
    ]
