# Generated by Django 5.2.3 on 2025-08-28 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('internet_plans', '0001_initial'),
        ('payments', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='payments.transaction'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['client', 'start_date'], name='internet_pl_client__50f516_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['internet_plan'], name='internet_pl_interne_32b724_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['is_active'], name='internet_pl_is_acti_9eba59_idx'),
        ),
    ]
