# Generated by Django 5.2.3 on 2026-02-02 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internet_plans', '0001_initial'),
        ('network_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='internetplan',
            name='allowed_routers',
            field=models.ManyToManyField(blank=True, help_text='Routers where this plan can be used (if router_specific)', related_name='allowed_plans', to='network_management.router'),
        ),
    ]
