# Generated by Django 5.2.3 on 2025-09-10 17:28

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('internet_plans', '0002_initial'),
        ('network_management', '0002_activationattempt_routerhealthcheck_and_more'),
        ('payments', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='internetplan',
            name='FUP_policy',
            field=models.TextField(blank=True, default='', help_text='Fair Usage Policy description for this plan'),
        ),
        migrations.AddField(
            model_name='internetplan',
            name='FUP_threshold',
            field=models.PositiveIntegerField(default=80, help_text='Usage percentage threshold after which speed may be reduced', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='internetplan',
            name='allowed_routers',
            field=models.ManyToManyField(blank=True, help_text='Routers where this plan can be activated (if router-specific)', to='network_management.router'),
        ),
        migrations.AddField(
            model_name='internetplan',
            name='bandwidth_limit',
            field=models.PositiveIntegerField(default=0, help_text='Bandwidth limit in kbps for router configuration (0 = unlimited)'),
        ),
        migrations.AddField(
            model_name='internetplan',
            name='concurrent_connections',
            field=models.PositiveIntegerField(default=1, help_text='Maximum number of simultaneous connections allowed'),
        ),
        migrations.AddField(
            model_name='internetplan',
            name='priority_level',
            field=models.IntegerField(choices=[(1, 'Lowest'), (2, 'Low'), (3, 'Medium'), (4, 'High'), (5, 'Highest'), (6, 'Critical'), (7, 'Premium'), (8, 'VIP')], default=4, help_text='Quality of Service priority level (higher = better service)'),
        ),
        migrations.AddField(
            model_name='internetplan',
            name='router_specific',
            field=models.BooleanField(default=False, help_text='If enabled, this plan can only be used on selected routers'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='data_used',
            field=models.BigIntegerField(default=0, help_text='Total data used in bytes'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='last_activity',
            field=models.DateTimeField(auto_now=True, help_text='Last time this subscription was active'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='mac_address',
            field=models.CharField(blank=True, help_text='MAC address of the device using this subscription', max_length=17, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='remaining_data',
            field=models.BigIntegerField(default=0, help_text='Remaining data in bytes'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='remaining_time',
            field=models.PositiveIntegerField(default=0, help_text='Remaining time in seconds'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='router',
            field=models.ForeignKey(blank=True, help_text='Router where this subscription is active', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='network_management.router'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('suspended', 'Suspended'), ('cancelled', 'Cancelled')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='subscription',
            name='time_used',
            field=models.PositiveIntegerField(default=0, help_text='Total time used in seconds'),
        ),
        migrations.AddIndex(
            model_name='internetplan',
            index=models.Index(fields=['bandwidth_limit'], name='internet_pl_bandwid_4d6c47_idx'),
        ),
        migrations.AddIndex(
            model_name='internetplan',
            index=models.Index(fields=['priority_level'], name='internet_pl_priorit_7f513c_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['status'], name='internet_pl_status_54a8b2_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['mac_address'], name='internet_pl_mac_add_d1715b_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['router'], name='internet_pl_router__918104_idx'),
        ),
    ]
