# Generated by Django 5.2.3 on 2026-02-04 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internet_plans', '0002_internetplan_allowed_routers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='internetplan',
            old_name='FUP_policy',
            new_name='fup_policy',
        ),
        migrations.RenameField(
            model_name='internetplan',
            old_name='FUP_threshold',
            new_name='fup_threshold',
        ),
        migrations.AlterField(
            model_name='internetplan',
            name='category',
            field=models.CharField(choices=[('residential', 'Residential'), ('business', 'Business'), ('promotional', 'Promotional'), ('enterprise', 'Enterprise')], db_index=True, default='residential', max_length=20),
        ),
        migrations.AlterField(
            model_name='plantemplate',
            name='category',
            field=models.CharField(choices=[('residential', 'Residential'), ('business', 'Business'), ('promotional', 'Promotional'), ('enterprise', 'Enterprise')], db_index=True, default='residential', max_length=20),
        ),
    ]
