# Generated by Django 5.2.3 on 2025-10-29 09:30

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_initial_mysql_fix'),
        ('internet_plans', '0002_add_foreign_keys'),
        ('network_management', '0002_add_foreign_keys'),
        ('payments', '0002_add_foreign_keys'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Unique name identifying the template', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, default='', help_text='Description of the template and its use cases')),
                ('category', models.CharField(choices=[('Residential', 'Residential'), ('Business', 'Business'), ('Promotional', 'Promotional'), ('Enterprise', 'Enterprise')], default='Residential', help_text='Target audience for this template', max_length=20)),
                ('base_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Base price suggestion for this template', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('access_methods', models.JSONField(default=dict, help_text='Configuration for Hotspot and PPPoE access methods')),
                ('is_public', models.BooleanField(default=True, help_text='Whether this template is available to all users')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this template is active and can be used')),
                ('usage_count', models.PositiveIntegerField(default=0, help_text='Number of times this template has been used')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when this template was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when this template was last updated')),
            ],
            options={
                'verbose_name': 'Plan Template',
                'verbose_name_plural': 'Plan Templates',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='plananalytics',
            name='plan',
        ),
        migrations.RemoveIndex(
            model_name='internetplan',
            name='internet_pl_bandwid_4d6c47_idx',
        ),
        migrations.RemoveIndex(
            model_name='internetplan',
            name='internet_pl_priorit_7f513c_idx',
        ),
        migrations.RemoveField(
            model_name='internetplan',
            name='bandwidth_limit',
        ),
        migrations.RemoveField(
            model_name='internetplan',
            name='concurrent_connections',
        ),
        migrations.RemoveField(
            model_name='internetplan',
            name='data_limit_unit',
        ),
        migrations.RemoveField(
            model_name='internetplan',
            name='data_limit_value',
        ),
        migrations.RemoveField(
            model_name='internetplan',
            name='download_speed_unit',
        ),
        migrations.RemoveField(
            model_name='internetplan',
            name='download_speed_value',
        ),
        migrations.RemoveField(
            model_name='internetplan',
            name='expiry_unit',
        ),
        migrations.RemoveField(
            model_name='internetplan',
            name='expiry_value',
        ),
        migrations.RemoveField(
            model_name='internetplan',
            name='upload_speed_unit',
        ),
        migrations.RemoveField(
            model_name='internetplan',
            name='upload_speed_value',
        ),
        migrations.RemoveField(
            model_name='internetplan',
            name='usage_limit_unit',
        ),
        migrations.RemoveField(
            model_name='internetplan',
            name='usage_limit_value',
        ),
        migrations.AddField(
            model_name='internetplan',
            name='access_methods',
            field=models.JSONField(default=dict, help_text='Configuration for Hotspot and PPPoE access methods'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='access_method',
            field=models.CharField(choices=[('hotspot', 'Hotspot'), ('pppoe', 'PPPoE')], default='hotspot', help_text='Access method used for this subscription', max_length=10),
        ),
        migrations.AlterField(
            model_name='internetplan',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Detailed description of the plan features'),
        ),
        migrations.AlterField(
            model_name='internetplan',
            name='priority_level',
            field=models.IntegerField(choices=[(1, 'Lowest'), (2, 'Low'), (3, 'Medium'), (4, 'High'), (5, 'Highest'), (6, 'Critical'), (7, 'Premium'), (8, 'VIP')], default=4, help_text='Quality of Service priority level'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['access_method'], name='internet_pl_access__81a05b_idx'),
        ),
        migrations.AddField(
            model_name='plantemplate',
            name='created_by',
            field=models.ForeignKey(help_text='User who created this template', on_delete=django.db.models.deletion.CASCADE, related_name='created_templates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='internetplan',
            name='template',
            field=models.ForeignKey(blank=True, help_text='Template used to create this plan', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_plans', to='internet_plans.plantemplate'),
        ),
        migrations.AddIndex(
            model_name='internetplan',
            index=models.Index(fields=['template'], name='internet_pl_templat_284aa7_idx'),
        ),
        migrations.DeleteModel(
            name='PlanAnalytics',
        ),
        migrations.AddIndex(
            model_name='plantemplate',
            index=models.Index(fields=['name'], name='internet_pl_name_90e57d_idx'),
        ),
        migrations.AddIndex(
            model_name='plantemplate',
            index=models.Index(fields=['category'], name='internet_pl_categor_5c97ff_idx'),
        ),
        migrations.AddIndex(
            model_name='plantemplate',
            index=models.Index(fields=['is_public'], name='internet_pl_is_publ_82d326_idx'),
        ),
        migrations.AddIndex(
            model_name='plantemplate',
            index=models.Index(fields=['is_active'], name='internet_pl_is_acti_794435_idx'),
        ),
        migrations.AddIndex(
            model_name='plantemplate',
            index=models.Index(fields=['created_at'], name='internet_pl_created_e061b6_idx'),
        ),
    ]
