# Generated by Django 5.2.3 on 2025-10-31 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internet_plans', '0003_plantemplate_remove_plananalytics_plan_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internetplan',
            name='features',
        ),
        migrations.RemoveField(
            model_name='internetplan',
            name='restrictions',
        ),
    ]
