# Generated by Django 5.2.3 on 2026-02-08 14:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internet_plans', '0003_rename_fup_policy_internetplan_fup_policy_and_more'),
        ('network_management', '0002_bandwidthallocation_transaction_hotspotuser_plan_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='internetplan',
            name='category',
            field=models.CharField(choices=[('Residential', 'Residential'), ('Business', 'Business'), ('Promotional', 'Promotional'), ('Enterprise', 'Enterprise')], db_index=True, default='residential', max_length=20),
        ),
        migrations.AlterField(
            model_name='internetplan',
            name='plan_type',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Free_trial', 'Free Trial'), ('Promotional', 'Promotional')], db_index=True, default='paid', max_length=20),
        ),
        migrations.AlterField(
            model_name='plantemplate',
            name='category',
            field=models.CharField(choices=[('Residential', 'Residential'), ('Business', 'Business'), ('Promotional', 'Promotional'), ('Enterprise', 'Enterprise')], db_index=True, default='residential', max_length=20),
        ),
        migrations.AddIndex(
            model_name='internetplan',
            index=models.Index(fields=['priority_level', 'active'], name='internet_pl_priorit_f94b7f_idx'),
        ),
        migrations.AddIndex(
            model_name='plantemplate',
            index=models.Index(fields=['usage_count'], name='internet_pl_usage_c_1d14d9_idx'),
        ),
        migrations.AddIndex(
            model_name='timevariantconfig',
            index=models.Index(fields=['is_active', 'created_at'], name='internet_pl_is_acti_e34259_idx'),
        ),
        migrations.AddIndex(
            model_name='timevariantconfig',
            index=models.Index(fields=['schedule_active', 'schedule_end_date'], name='internet_pl_schedul_bda93f_idx'),
        ),
    ]
