# Generated by Django 5.2.3 on 2025-11-18 10:19

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_initial_mysql_fix'),
        ('internet_plans', '0004_remove_internetplan_features_and_more'),
        ('network_management', '0005_remove_router_hotspot_config_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='transaction',
        ),
        migrations.AddField(
            model_name='subscription',
            name='activation_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='activation_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscription',
            name='activation_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='activation_successful',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscription',
            name='transaction_reference',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='internetplan',
            name='FUP_policy',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='internetplan',
            name='FUP_threshold',
            field=models.PositiveIntegerField(default=80, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='internetplan',
            name='access_methods',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='internetplan',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='internetplan',
            name='allowed_routers',
            field=models.ManyToManyField(blank=True, related_name='allowed_plans', to='network_management.router'),
        ),
        migrations.AlterField(
            model_name='internetplan',
            name='category',
            field=models.CharField(choices=[('Residential', 'Residential'), ('Business', 'Business'), ('Promotional', 'Promotional'), ('Enterprise', 'Enterprise')], default='Residential', max_length=20),
        ),
        migrations.AlterField(
            model_name='internetplan',
            name='client_sessions',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='internetplan',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='internetplan',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='internetplan',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='internetplan',
            name='plan_type',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Free Trial', 'Free Trial')], default='Paid', max_length=20),
        ),
        migrations.AlterField(
            model_name='internetplan',
            name='price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='internetplan',
            name='priority_level',
            field=models.IntegerField(choices=[(1, 'Lowest'), (2, 'Low'), (3, 'Medium'), (4, 'High'), (5, 'Highest'), (6, 'Critical'), (7, 'Premium'), (8, 'VIP')], default=4),
        ),
        migrations.AlterField(
            model_name='internetplan',
            name='purchases',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='internetplan',
            name='router_specific',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='internetplan',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_plans', to='internet_plans.plantemplate'),
        ),
        migrations.AlterField(
            model_name='internetplan',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='plantemplate',
            name='access_methods',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='plantemplate',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='plantemplate',
            name='category',
            field=models.CharField(choices=[('Residential', 'Residential'), ('Business', 'Business'), ('Promotional', 'Promotional'), ('Enterprise', 'Enterprise')], default='Residential', max_length=20),
        ),
        migrations.AlterField(
            model_name='plantemplate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='plantemplate',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_templates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='plantemplate',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='plantemplate',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='plantemplate',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='plantemplate',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='plantemplate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='plantemplate',
            name='usage_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='access_method',
            field=models.CharField(choices=[('hotspot', 'Hotspot'), ('pppoe', 'PPPoE')], default='hotspot', max_length=10),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='data_used',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='last_activity',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='mac_address',
            field=models.CharField(blank=True, max_length=17, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='remaining_data',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='remaining_time',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='router',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='network_management.router'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Payment'), ('active', 'Active'), ('expired', 'Expired'), ('suspended', 'Suspended'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='time_used',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['transaction_reference'], name='internet_pl_transac_55243c_idx'),
        ),
    ]
