# Generated by Django 5.2.3 on 2026-02-16 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internet_plans', '0004_alter_internetplan_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internetplan',
            name='category',
            field=models.CharField(choices=[('Residential', 'Residential'), ('Business', 'Business'), ('Promotional', 'Promotional'), ('Enterprise', 'Enterprise')], db_index=True, default='Residential', max_length=20),
        ),
        migrations.AlterField(
            model_name='internetplan',
            name='plan_type',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Free_trial', 'Free Trial'), ('Promotional', 'Promotional')], db_index=True, default='Paid', max_length=20),
        ),
        migrations.AlterField(
            model_name='plantemplate',
            name='category',
            field=models.CharField(choices=[('Residential', 'Residential'), ('Business', 'Business'), ('Promotional', 'Promotional'), ('Enterprise', 'Enterprise')], db_index=True, default='Residential', max_length=20),
        ),
    ]
