# Generated by Django 5.1.3 on 2025-01-28 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MpesaCallback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event",
                    models.CharField(
                        choices=[
                            ("Payment Success", "Payment Success"),
                            ("Payment Failure", "Payment Failure"),
                            ("Transaction Cancellation", "Transaction Cancellation"),
                        ],
                        max_length=50,
                    ),
                ),
                ("url", models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name="MpesaConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("apiKey", models.CharField(max_length=255)),
                ("secretKey", models.CharField(max_length=255)),
                ("shortCode", models.CharField(max_length=10)),
                ("passKey", models.CharField(max_length=255)),
                ("callbackURL", models.URLField()),
                ("validationURL", models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name="MpesaTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("transaction_id", models.CharField(max_length=50, unique=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Success", "Success"),
                            ("Pending", "Pending"),
                            ("Failed", "Failed"),
                        ],
                        max_length=20,
                    ),
                ),
                ("date", models.DateTimeField()),
                ("user", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="PaymentTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Matched", "Matched"),
                            ("Pending", "Pending"),
                            ("Discrepancy", "Discrepancy"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("Payment", "Payment")],
                        default="Payment",
                        max_length=50,
                    ),
                ),
                ("reference", models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
