# Generated by Django 5.2.3 on 2025-09-19 07:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('internet_plans', '0002_add_foreign_keys'),
        ('network_management', '0002_add_foreign_keys'),
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mpesacallbackconfiguration',
            options={'ordering': ['router__name', 'event__priority']},
        ),
        migrations.AddField(
            model_name='mpesacallbackconfiguration',
            name='router',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mpesa_callbacks', to='network_management.router'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='internet_plans.internetplan'),
        ),
        migrations.AddField(
            model_name='transactionlog',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='internet_plans.subscription'),
        ),
        migrations.AlterUniqueTogether(
            name='mpesacallbackconfiguration',
            unique_together={('router', 'event')},
        ),
        migrations.AddIndex(
            model_name='mpesacallbackconfiguration',
            index=models.Index(fields=['router', 'event'], name='payments_mp_router__0a28fa_idx'),
        ),
        migrations.AddIndex(
            model_name='transactionlog',
            index=models.Index(fields=['subscription'], name='payments_tr_subscri_634e3c_idx'),
        ),
    ]
