# Generated by Django 5.2.3 on 2025-08-28 14:12

import django.core.validators
import django.db.models.deletion
import payments.models.payment_config_model
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('internet_plans', '0001_initial'),
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentGateway',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[('mpesa_paybill', 'M-Pesa Paybill'), ('mpesa_till', 'M-Pesa Till'), ('bank_transfer', 'Bank Transfer'), ('paypal', 'PayPal')], default='paypal', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('sandbox_mode', models.BooleanField(default=True)),
                ('security_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('transaction_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('auto_settle', models.BooleanField(default=True)),
                ('webhook_secret', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_payment_gateways', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment Gateway',
                'verbose_name_plural': 'Payment Gateways',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MpesaConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('consumer_key', models.TextField()),
                ('consumer_secret', models.TextField()),
                ('passkey', models.TextField()),
                ('paybill_number', models.CharField(blank=True, max_length=20, null=True)),
                ('till_number', models.CharField(blank=True, max_length=20, null=True)),
                ('callback_url', models.URLField(max_length=500)),
                ('initiator_name', models.CharField(blank=True, max_length=100, null=True)),
                ('security_credential', models.TextField(blank=True, null=True)),
                ('gateway', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mpesaconfig', to='payments.paymentgateway')),
            ],
            options={
                'verbose_name': 'M-Pesa Configuration',
                'verbose_name_plural': 'M-Pesa Configurations',
            },
            bases=(payments.models.payment_config_model.FernetEncryptedMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ClientPaymentMethod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to='account.client')),
                ('gateway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_methods', to='payments.paymentgateway')),
            ],
            options={
                'verbose_name': 'Client Payment Method',
                'verbose_name_plural': 'Client Payment Methods',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BankConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bank_name', models.CharField(max_length=100)),
                ('account_name', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=50)),
                ('branch_code', models.CharField(blank=True, max_length=20, null=True)),
                ('swift_code', models.CharField(blank=True, max_length=20, null=True)),
                ('iban', models.CharField(blank=True, max_length=50, null=True)),
                ('bank_code', models.CharField(blank=True, max_length=20, null=True)),
                ('gateway', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bankconfig', to='payments.paymentgateway')),
            ],
            options={
                'verbose_name': 'Bank Configuration',
                'verbose_name_plural': 'Bank Configurations',
            },
        ),
        migrations.CreateModel(
            name='PayPalConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_id', models.TextField()),
                ('secret', models.TextField()),
                ('merchant_id', models.TextField(blank=True, null=True)),
                ('callback_url', models.URLField(max_length=500)),
                ('webhook_id', models.CharField(blank=True, max_length=100, null=True)),
                ('bn_code', models.CharField(blank=True, max_length=50, null=True)),
                ('gateway', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='paypalconfig', to='payments.paymentgateway')),
            ],
            options={
                'verbose_name': 'PayPal Configuration',
                'verbose_name_plural': 'PayPal Configurations',
            },
            bases=(payments.models.payment_config_model.FernetEncryptedMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reference', models.CharField(blank=True, max_length=100, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='account.client')),
                ('gateway', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='payments.paymentgateway')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='internet_plans.internetplan')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebhookLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=100)),
                ('payload', models.JSONField()),
                ('headers', models.JSONField()),
                ('ip_address', models.GenericIPAddressField()),
                ('status_code', models.PositiveSmallIntegerField()),
                ('response', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('gateway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_logs', to='payments.paymentgateway')),
            ],
            options={
                'verbose_name': 'Webhook Log',
                'verbose_name_plural': 'Webhook Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ConfigurationHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('activate', 'Activate'), ('deactivate', 'Deactivate'), ('test', 'Test Connection')], max_length=20)),
                ('model', models.CharField(max_length=50)),
                ('object_id', models.CharField(max_length=36)),
                ('changes', models.JSONField(default=list)),
                ('old_values', models.JSONField(default=dict)),
                ('new_values', models.JSONField(default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_config_changes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuration History',
                'verbose_name_plural': 'Configuration Histories',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['model', 'object_id'], name='payments_co_model_861578_idx'), models.Index(fields=['timestamp'], name='payments_co_timesta_5bdc82_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='paymentgateway',
            index=models.Index(fields=['name', 'is_active'], name='payments_pa_name_1477a5_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentgateway',
            index=models.Index(fields=['security_level'], name='payments_pa_securit_e0552f_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentgateway',
            index=models.Index(fields=['created_at'], name='payments_pa_created_68fc05_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='clientpaymentmethod',
            unique_together={('client', 'gateway')},
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['reference'], name='payments_tr_referen_530efe_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['status'], name='payments_tr_status_96e6c0_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['created_at'], name='payments_tr_created_02ae92_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['client', 'gateway'], name='payments_tr_client__f218f9_idx'),
        ),
    ]
