# Generated by Django 5.1.3 on 2025-06-03 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="bank_reference",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="transaction",
            name="paypal_transaction_id",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="phone_number",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
