# Generated by Django 5.2.3 on 2025-11-18 10:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_initial_mysql_fix'),
        ('internet_plans', '0005_remove_subscription_transaction_and_more'),
        ('payments', '0002_add_foreign_keys'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CallbackDeliveryLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payload', models.JSONField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('retrying', 'Retrying')], default='pending', max_length=20)),
                ('response_status', models.IntegerField(blank=True, null=True)),
                ('response_body', models.TextField(blank=True)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Callback Delivery Log',
                'verbose_name_plural': 'Callback Delivery Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('successful_transactions', models.PositiveIntegerField(default=0)),
                ('failed_transactions', models.PositiveIntegerField(default=0)),
                ('pending_transactions', models.PositiveIntegerField(default=0)),
                ('success_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('total_transactions', models.PositiveIntegerField(default=0)),
                ('revenue_by_gateway', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Payment Analytics',
                'verbose_name_plural': 'Payment Analytics',
                'ordering': ['-date'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='mpesacallbackconfiguration',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='mpesacallbackconfiguration',
            name='event',
        ),
        migrations.RemoveField(
            model_name='mpesacallbackconfiguration',
            name='router',
        ),
        migrations.RemoveField(
            model_name='mpesacallbackconfiguration',
            name='security_profile',
        ),
        migrations.RemoveField(
            model_name='mpesacallbacklog',
            name='configuration',
        ),
        migrations.RemoveField(
            model_name='mpesacallbackrule',
            name='target_configuration',
        ),
        migrations.RemoveField(
            model_name='mpesacallbacklog',
            name='transaction',
        ),
        migrations.RemoveIndex(
            model_name='transactionlog',
            name='payments_tr_subscri_634e3c_idx',
        ),
        migrations.RemoveField(
            model_name='transactionlog',
            name='subscription',
        ),
        migrations.AddField(
            model_name='paymentgateway',
            name='health_status',
            field=models.CharField(choices=[('healthy', 'Healthy'), ('degraded', 'Degraded'), ('unhealthy', 'Unhealthy'), ('unknown', 'Unknown')], default='unknown', max_length=20),
        ),
        migrations.AddField(
            model_name='paymentgateway',
            name='last_health_check',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='callback_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='transaction',
            name='idempotency_key',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='last_callback_attempt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='internet_plans.subscription'),
        ),
        migrations.AddField(
            model_name='transactionlog',
            name='subscription_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='webhooklog',
            name='signature_valid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='internet_plans.internetplan'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('cancelled', 'Cancelled'), ('verifying', 'Verifying')], default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='paymentgateway',
            index=models.Index(fields=['health_status'], name='payments_pa_health__31a96f_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['idempotency_key'], name='payments_tr_idempot_801f50_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['plan_id'], name='payments_tr_plan_id_5a2e4a_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['subscription_id'], name='payments_tr_subscri_b3b6ae_idx'),
        ),
        migrations.AddIndex(
            model_name='transactionlog',
            index=models.Index(fields=['subscription_id'], name='payments_tr_subscri_634e3c_idx'),
        ),
        migrations.AddField(
            model_name='callbackdeliverylog',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='callback_deliveries', to='payments.transaction'),
        ),
        migrations.AddIndex(
            model_name='paymentanalytics',
            index=models.Index(fields=['date'], name='payments_pa_date_d19349_idx'),
        ),
        migrations.DeleteModel(
            name='MpesaCallbackEvent',
        ),
        migrations.DeleteModel(
            name='MpesaCallbackSecurityProfile',
        ),
        migrations.DeleteModel(
            name='MpesaCallbackConfiguration',
        ),
        migrations.DeleteModel(
            name='MpesaCallbackRule',
        ),
        migrations.DeleteModel(
            name='MpesaCallbackLog',
        ),
        migrations.AddIndex(
            model_name='callbackdeliverylog',
            index=models.Index(fields=['transaction', 'status'], name='payments_ca_transac_5ff0fd_idx'),
        ),
        migrations.AddIndex(
            model_name='callbackdeliverylog',
            index=models.Index(fields=['created_at'], name='payments_ca_created_f39f9d_idx'),
        ),
    ]
