# Generated by Django 5.2.3 on 2025-09-12 11:37

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('payments', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=10)),
                ('payment_method', models.CharField(choices=[('mpesa', 'M-Pesa'), ('paypal', 'PayPal'), ('bank_transfer', 'Bank Transfer')], default='mpesa', max_length=15)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('reference_number', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_logs', to='account.client')),
                ('payment_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='payments.transaction')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transaction Log',
                'verbose_name_plural': 'Transaction Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TransactionLogHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('status_change', 'Status Change'), ('refund', 'Refund')], max_length=15)),
                ('old_status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('refunded', 'Refunded')], max_length=10, null=True)),
                ('new_status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('refunded', 'Refunded')], max_length=10, null=True)),
                ('changes', models.JSONField(default=dict)),
                ('notes', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('transaction_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='payments.transactionlog')),
            ],
            options={
                'verbose_name': 'Transaction Log History',
                'verbose_name_plural': 'Transaction Log Histories',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='transactionlog',
            index=models.Index(fields=['transaction_id'], name='payments_tr_transac_1fe1c9_idx'),
        ),
        migrations.AddIndex(
            model_name='transactionlog',
            index=models.Index(fields=['status'], name='payments_tr_status_000922_idx'),
        ),
        migrations.AddIndex(
            model_name='transactionlog',
            index=models.Index(fields=['created_at'], name='payments_tr_created_714f6a_idx'),
        ),
        migrations.AddIndex(
            model_name='transactionlog',
            index=models.Index(fields=['client', 'payment_method'], name='payments_tr_client__56b036_idx'),
        ),
        migrations.AddIndex(
            model_name='transactionlog',
            index=models.Index(fields=['phone_number'], name='payments_tr_phone_n_cdc9e8_idx'),
        ),
    ]
