# Generated by Django 5.2.3 on 2025-11-18 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_callbackdeliverylog_paymentanalytics_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankconfig',
            name='account_type',
            field=models.CharField(choices=[('checking', 'Checking Account'), ('savings', 'Savings Account'), ('business', 'Business Account'), ('corporate', 'Corporate Account')], default='checking', max_length=20),
        ),
        migrations.AddField(
            model_name='bankconfig',
            name='bank_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bankconfig',
            name='currency',
            field=models.CharField(choices=[('KES', 'Kenyan Shilling'), ('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound')], default='KES', max_length=3),
        ),
        migrations.AddField(
            model_name='bankconfig',
            name='routing_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
