# Generated by Django 5.2.3 on 2025-11-19 11:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_initial_mysql_fix'),
        ('internet_plans', '0005_remove_subscription_transaction_and_more'),
        ('payments', '0004_bankconfig_account_type_bankconfig_bank_address_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='transactionlog',
            name='payments_tr_subscri_634e3c_idx',
        ),
        migrations.RemoveField(
            model_name='transactionlog',
            name='subscription_id',
        ),
        migrations.AddField(
            model_name='transactionlog',
            name='access_type',
            field=models.CharField(choices=[('hotspot', 'Hotspot'), ('pppoe', 'PPPoE'), ('both', 'Both')], default='hotspot', help_text='Type of access method (Hotspot/PPPoE)', max_length=10),
        ),
        migrations.AddField(
            model_name='transactionlog',
            name='internet_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction_logs', to='internet_plans.internetplan'),
        ),
        migrations.AddField(
            model_name='transactionlog',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction_logs', to='internet_plans.subscription'),
        ),
        migrations.AddField(
            model_name='transactionloghistory',
            name='new_access_type',
            field=models.CharField(blank=True, choices=[('hotspot', 'Hotspot'), ('pppoe', 'PPPoE'), ('both', 'Both')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='transactionloghistory',
            name='old_access_type',
            field=models.CharField(blank=True, choices=[('hotspot', 'Hotspot'), ('pppoe', 'PPPoE'), ('both', 'Both')], max_length=10, null=True),
        ),
        migrations.AddIndex(
            model_name='transactionlog',
            index=models.Index(fields=['access_type'], name='payments_tr_access__1679c5_idx'),
        ),
        migrations.AddIndex(
            model_name='transactionlog',
            index=models.Index(fields=['internet_plan'], name='payments_tr_interne_20ab51_idx'),
        ),
        migrations.AddIndex(
            model_name='transactionlog',
            index=models.Index(fields=['subscription'], name='payments_tr_subscri_634e3c_idx'),
        ),
    ]
