# Generated by Django 5.2.3 on 2025-11-19 14:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_remove_transactionlog_payments_tr_subscri_634e3c_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='manualexpense',
            name='access_type',
            field=models.CharField(choices=[('hotspot', 'Hotspot'), ('pppoe', 'PPPoE'), ('both', 'Both'), ('general', 'General')], default='general', max_length=10),
        ),
        migrations.AddField(
            model_name='reconciliationreport',
            name='both_expenses',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='reconciliationreport',
            name='both_revenue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='reconciliationreport',
            name='both_tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='reconciliationreport',
            name='expense_breakdown',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='reconciliationreport',
            name='general_expenses',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='reconciliationreport',
            name='hotspot_expenses',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='reconciliationreport',
            name='hotspot_revenue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='reconciliationreport',
            name='hotspot_tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='reconciliationreport',
            name='pppoe_expenses',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='reconciliationreport',
            name='pppoe_revenue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='reconciliationreport',
            name='pppoe_tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='reconciliationreport',
            name='revenue_breakdown',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='reconciliationreport',
            name='tax_breakdown',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='reconciliationstats',
            name='both_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reconciliationstats',
            name='both_expenses',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='reconciliationstats',
            name='both_revenue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='reconciliationstats',
            name='general_expenses',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='reconciliationstats',
            name='hotspot_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reconciliationstats',
            name='hotspot_expenses',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='reconciliationstats',
            name='hotspot_revenue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='reconciliationstats',
            name='pppoe_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reconciliationstats',
            name='pppoe_expenses',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='reconciliationstats',
            name='pppoe_revenue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='taxconfiguration',
            name='access_type',
            field=models.CharField(choices=[('all', 'All Access Types'), ('hotspot', 'Hotspot Only'), ('pppoe', 'PPPoE Only'), ('both', 'Both Access Types')], default='all', max_length=10),
        ),
        migrations.AddIndex(
            model_name='manualexpense',
            index=models.Index(fields=['access_type'], name='payments_ma_access__05f02d_idx'),
        ),
        migrations.AddIndex(
            model_name='taxconfiguration',
            index=models.Index(fields=['access_type', 'is_enabled'], name='payments_ta_access__de4cc9_idx'),
        ),
    ]
