# Generated by Django 5.2.3 on 2025-11-20 08:58

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_manualexpense_access_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='expensecategory',
            name='is_predefined',
            field=models.BooleanField(default=False, help_text='Whether this is a system-defined category'),
        ),
        migrations.AlterField(
            model_name='manualexpense',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AddIndex(
            model_name='expensecategory',
            index=models.Index(fields=['is_active', 'is_predefined'], name='payments_ex_is_acti_fc2635_idx'),
        ),
    ]
