# Generated by Django 5.2.3 on 2025-11-20 11:22

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_expensecategory_is_predefined_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manualexpense',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
