# Generated by Django 5.2.3 on 2025-11-20 15:03

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_alter_manualexpense_amount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taxconfiguration',
            options={'ordering': ['name', '-created_at'], 'verbose_name': 'Tax Configuration', 'verbose_name_plural': 'Tax Configurations'},
        ),
        migrations.AddField(
            model_name='taxconfiguration',
            name='effective_from',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='When this tax configuration becomes effective'),
        ),
        migrations.AddField(
            model_name='taxconfiguration',
            name='effective_to',
            field=models.DateTimeField(blank=True, help_text='When this tax configuration expires (null means indefinite)', null=True),
        ),
        migrations.AddField(
            model_name='taxconfiguration',
            name='last_audited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taxconfiguration',
            name='requires_approval',
            field=models.BooleanField(default=False, help_text='Whether this tax requires special approval'),
        ),
        migrations.AddField(
            model_name='taxconfiguration',
            name='revision_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taxconfiguration',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('archived', 'Archived')], default='active', max_length=10),
        ),
        migrations.AddField(
            model_name='taxconfiguration',
            name='tax_code',
            field=models.CharField(blank=True, help_text='Official tax code or identifier', max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='taxconfiguration',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_taxes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taxconfiguration',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='taxconfiguration',
            name='name',
            field=models.CharField(help_text='Unique name for the tax configuration', max_length=100),
        ),
        migrations.AlterField(
            model_name='taxconfiguration',
            name='rate',
            field=models.DecimalField(decimal_places=4, help_text='Tax rate in percentage (0-100)', max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))]),
        ),
        migrations.AlterField(
            model_name='taxconfiguration',
            name='tax_type',
            field=models.CharField(choices=[('vat', 'VAT'), ('withholding', 'Withholding Tax'), ('custom', 'Custom Tax'), ('sales', 'Sales Tax'), ('service', 'Service Tax'), ('excise', 'Excise Duty')], default='custom', max_length=20),
        ),
        migrations.AddIndex(
            model_name='taxconfiguration',
            index=models.Index(fields=['tax_type', 'status'], name='payments_ta_tax_typ_759805_idx'),
        ),
        migrations.AddIndex(
            model_name='taxconfiguration',
            index=models.Index(fields=['effective_from', 'effective_to'], name='payments_ta_effecti_15e4de_idx'),
        ),
        migrations.AddIndex(
            model_name='taxconfiguration',
            index=models.Index(fields=['created_at'], name='payments_ta_created_4c501c_idx'),
        ),
        migrations.AddIndex(
            model_name='taxconfiguration',
            index=models.Index(fields=['updated_at'], name='payments_ta_updated_71c645_idx'),
        ),
        migrations.AddConstraint(
            model_name='taxconfiguration',
            constraint=models.UniqueConstraint(fields=('name', 'tax_type', 'access_type'), name='unique_tax_configuration'),
        ),
        migrations.AddConstraint(
            model_name='taxconfiguration',
            constraint=models.CheckConstraint(condition=models.Q(('rate__gte', 0), ('rate__lte', 100)), name='valid_tax_rate_range'),
        ),
    ]
