# Generated by Django 5.2.3 on 2025-11-20 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_alter_taxconfiguration_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxconfiguration',
            name='tax_code',
            field=models.CharField(blank=True, help_text='Official tax code or identifier', max_length=50, null=True, unique=True),
        ),
    ]
