# Generated by Django 5.1.3 on 2025-03-29 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Router",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("host", models.CharField(max_length=100)),
                ("user", models.CharField(max_length=50)),
                ("ssh_key", models.TextField(blank=True)),
                ("ssh_pub_key", models.TextField(blank=True)),
                ("port", models.PositiveIntegerField(default=22)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Connected", "Connected"),
                            ("Disconnected", "Disconnected"),
                        ],
                        default="Disconnected",
                        max_length=20,
                    ),
                ),
                ("uptime", models.CharField(default="N/A", max_length=50)),
                ("version", models.CharField(default="Unknown", max_length=20)),
                ("bandwidth", models.CharField(default="N/A", max_length=50)),
                ("cpu_usage", models.IntegerField(default=0)),
                ("active_clients", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Router",
                "verbose_name_plural": "Routers",
            },
        ),
    ]
