# Generated by Django 5.2.3 on 2026-02-02 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internet_plans', '0002_internetplan_allowed_routers'),
        ('network_management', '0001_initial'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bandwidthallocation',
            name='transaction',
            field=models.ForeignKey(blank=True, help_text='Transaction associated with this allocation', null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.transaction'),
        ),
        migrations.AddField(
            model_name='hotspotuser',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='internet_plans.internetplan'),
        ),
        migrations.AddField(
            model_name='hotspotuser',
            name='transaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.transaction'),
        ),
        migrations.AddField(
            model_name='pppoeuser',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='internet_plans.internetplan'),
        ),
        migrations.AddField(
            model_name='pppoeuser',
            name='transaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.transaction'),
        ),
    ]
