# Generated by Django 5.2.3 on 2026-01-22 14:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('internet_plans', '0002_internetplan_allowed_routers'),
        ('network_management', '0001_initial'),
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bandwidthallocation',
            name='transaction',
            field=models.ForeignKey(blank=True, help_text='Transaction associated with this allocation', null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.transaction'),
        ),
        migrations.AddField(
            model_name='bandwidthusagehistory',
            name='allocation',
            field=models.ForeignKey(help_text='Associated bandwidth allocation', on_delete=django.db.models.deletion.CASCADE, related_name='usage_history', to='network_management.bandwidthallocation'),
        ),
        migrations.AddField(
            model_name='bulkoperation',
            name='initiated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dhcplease',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hotspotuser',
            name='client',
            field=models.ForeignKey(limit_choices_to={'user_type': 'client'}, on_delete=django.db.models.deletion.CASCADE, related_name='hotspot_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hotspotuser',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='internet_plans.internetplan'),
        ),
        migrations.AddField(
            model_name='hotspotuser',
            name='transaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.transaction'),
        ),
        migrations.AddField(
            model_name='ipaddress',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.client'),
        ),
        migrations.AddField(
            model_name='diagnostictest',
            name='client_ip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnostic_tests', to='network_management.ipaddress'),
        ),
        migrations.AddField(
            model_name='dhcplease',
            name='ip_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dhcp_leases', to='network_management.ipaddress'),
        ),
        migrations.AddField(
            model_name='networkalert',
            name='related_test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='network_management.diagnostictest'),
        ),
        migrations.AddField(
            model_name='pppoeuser',
            name='client',
            field=models.ForeignKey(limit_choices_to={'user_type': 'client'}, on_delete=django.db.models.deletion.CASCADE, related_name='pppoe_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pppoeuser',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='internet_plans.internetplan'),
        ),
        migrations.AddField(
            model_name='pppoeuser',
            name='transaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.transaction'),
        ),
        migrations.AddIndex(
            model_name='qosprofile',
            index=models.Index(fields=['name', 'priority'], name='network_man_name_525c66_idx'),
        ),
        migrations.AddIndex(
            model_name='qosprofile',
            index=models.Index(fields=['is_active'], name='network_man_is_acti_f149a9_idx'),
        ),
        migrations.AddField(
            model_name='bandwidthallocation',
            name='qos_profile',
            field=models.ForeignKey(blank=True, help_text='QoS profile applied to this allocation', null=True, on_delete=django.db.models.deletion.SET_NULL, to='network_management.qosprofile'),
        ),
        migrations.AddIndex(
            model_name='router',
            index=models.Index(fields=['status', 'is_active'], name='network_man_status_982d51_idx'),
        ),
        migrations.AddIndex(
            model_name='router',
            index=models.Index(fields=['type'], name='network_man_type_184e84_idx'),
        ),
        migrations.AddIndex(
            model_name='router',
            index=models.Index(fields=['ssid'], name='network_man_ssid_e90f3d_idx'),
        ),
        migrations.AddIndex(
            model_name='router',
            index=models.Index(fields=['connection_status'], name='network_man_connect_5fe1af_idx'),
        ),
        migrations.AddIndex(
            model_name='router',
            index=models.Index(fields=['configuration_status'], name='network_man_configu_397454_idx'),
        ),
        migrations.AddIndex(
            model_name='router',
            index=models.Index(fields=['last_connection_test'], name='network_man_last_co_bb438a_idx'),
        ),
        migrations.AddIndex(
            model_name='router',
            index=models.Index(fields=['vpn_enabled', 'vpn_type'], name='network_man_vpn_ena_78425c_idx'),
        ),
        migrations.AddField(
            model_name='pppoeuser',
            name='router',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pppoe_users', to='network_management.router'),
        ),
        migrations.AddField(
            model_name='pppoeconfiguration',
            name='router',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pppoe_configurations', to='network_management.router'),
        ),
        migrations.AddField(
            model_name='networkalert',
            name='router',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='network_management.router'),
        ),
        migrations.AddField(
            model_name='ipaddress',
            name='router',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ip_addresses', to='network_management.router'),
        ),
        migrations.AddField(
            model_name='hotspotuser',
            name='router',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotspot_users', to='network_management.router'),
        ),
        migrations.AddField(
            model_name='hotspotconfiguration',
            name='router',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotspot_configurations', to='network_management.router'),
        ),
        migrations.AddField(
            model_name='diagnostictest',
            name='router',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnostic_tests', to='network_management.router'),
        ),
        migrations.AddField(
            model_name='bulkoperation',
            name='routers',
            field=models.ManyToManyField(related_name='bulk_operations', to='network_management.router'),
        ),
        migrations.AddField(
            model_name='activationattempt',
            name='router',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='network_management.router'),
        ),
        migrations.AddField(
            model_name='routerauditlog',
            name='router',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='network_management.router'),
        ),
        migrations.AddField(
            model_name='routerauditlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='routercallbackconfig',
            name='router',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='callback_configs', to='network_management.router'),
        ),
        migrations.AddField(
            model_name='routerconnectiontest',
            name='router',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connection_tests', to='network_management.router'),
        ),
        migrations.AddField(
            model_name='routerconnectiontest',
            name='tested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='routerhealthcheck',
            name='router',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_checks', to='network_management.router'),
        ),
        migrations.AddField(
            model_name='routersessionhistory',
            name='hotspot_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='session_history', to='network_management.hotspotuser'),
        ),
        migrations.AddField(
            model_name='routersessionhistory',
            name='pppoe_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='session_history', to='network_management.pppoeuser'),
        ),
        migrations.AddField(
            model_name='routersessionhistory',
            name='router',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='network_management.router'),
        ),
        migrations.AddField(
            model_name='routerstats',
            name='router',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='network_management.router'),
        ),
        migrations.AddIndex(
            model_name='serviceoperationactivation',
            index=models.Index(fields=['service_operation_id'], name='network_man_service_9d6843_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceoperationactivation',
            index=models.Index(fields=['subscription_id'], name='network_man_subscri_1711b7_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceoperationactivation',
            index=models.Index(fields=['status', 'created_at'], name='network_man_status_f089f5_idx'),
        ),
        migrations.AddField(
            model_name='speedtesthistory',
            name='client_ip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='speed_test_history', to='network_management.ipaddress'),
        ),
        migrations.AddField(
            model_name='speedtesthistory',
            name='router',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speed_test_history', to='network_management.router'),
        ),
        migrations.AddField(
            model_name='subnet',
            name='router',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subnets', to='network_management.router'),
        ),
        migrations.AddIndex(
            model_name='bandwidthusagehistory',
            index=models.Index(fields=['allocation', 'timestamp'], name='network_man_allocat_556bea_idx'),
        ),
        migrations.AddIndex(
            model_name='bandwidthusagehistory',
            index=models.Index(fields=['timestamp'], name='network_man_timesta_1c706f_idx'),
        ),
        migrations.AddIndex(
            model_name='dhcplease',
            index=models.Index(fields=['ip_address', 'is_active'], name='network_man_ip_addr_40ae75_idx'),
        ),
        migrations.AddIndex(
            model_name='dhcplease',
            index=models.Index(fields=['mac_address'], name='network_man_mac_add_bb5f0c_idx'),
        ),
        migrations.AddIndex(
            model_name='dhcplease',
            index=models.Index(fields=['expires_at'], name='network_man_expires_3e9f46_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dhcplease',
            unique_together={('ip_address', 'mac_address')},
        ),
        migrations.AddIndex(
            model_name='bandwidthallocation',
            index=models.Index(fields=['client', 'status'], name='network_man_client__0fb286_idx'),
        ),
        migrations.AddIndex(
            model_name='bandwidthallocation',
            index=models.Index(fields=['mac_address'], name='network_man_mac_add_fdcc64_idx'),
        ),
        migrations.AddIndex(
            model_name='bandwidthallocation',
            index=models.Index(fields=['ip_address'], name='network_man_ip_addr_deb256_idx'),
        ),
        migrations.AddIndex(
            model_name='bandwidthallocation',
            index=models.Index(fields=['status'], name='network_man_status_2e6000_idx'),
        ),
        migrations.AddIndex(
            model_name='bandwidthallocation',
            index=models.Index(fields=['created_at'], name='network_man_created_048eba_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='bandwidthallocation',
            unique_together={('client', 'ip_address', 'mac_address')},
        ),
        migrations.AddIndex(
            model_name='pppoeuser',
            index=models.Index(fields=['username'], name='network_man_usernam_9220e1_idx'),
        ),
        migrations.AddIndex(
            model_name='pppoeuser',
            index=models.Index(fields=['session_id'], name='network_man_session_ee6e59_idx'),
        ),
        migrations.AddIndex(
            model_name='pppoeuser',
            index=models.Index(fields=['active'], name='network_man_active_7a047e_idx'),
        ),
        migrations.AddIndex(
            model_name='pppoeuser',
            index=models.Index(fields=['client', 'active'], name='network_man_client__97b468_idx'),
        ),
        migrations.AddIndex(
            model_name='pppoeuser',
            index=models.Index(fields=['router', 'active'], name='network_man_router__8409c5_idx'),
        ),
        migrations.AddIndex(
            model_name='pppoeuser',
            index=models.Index(fields=['pppoe_service_type'], name='network_man_pppoe_s_f31cc4_idx'),
        ),
        migrations.AddIndex(
            model_name='pppoeconfiguration',
            index=models.Index(fields=['router', 'service_name'], name='network_man_router__1bd03c_idx'),
        ),
        migrations.AddIndex(
            model_name='pppoeconfiguration',
            index=models.Index(fields=['configuration_applied'], name='network_man_configu_c54aaf_idx'),
        ),
        migrations.AddIndex(
            model_name='networkalert',
            index=models.Index(fields=['router', 'is_resolved'], name='network_man_router__8718be_idx'),
        ),
        migrations.AddIndex(
            model_name='networkalert',
            index=models.Index(fields=['severity'], name='network_man_severit_382b2e_idx'),
        ),
        migrations.AddIndex(
            model_name='networkalert',
            index=models.Index(fields=['created_at'], name='network_man_created_0b0353_idx'),
        ),
        migrations.AddIndex(
            model_name='ipaddress',
            index=models.Index(fields=['router', 'status'], name='network_man_router__b095bf_idx'),
        ),
        migrations.AddIndex(
            model_name='ipaddress',
            index=models.Index(fields=['ip_address'], name='network_man_ip_addr_addf6c_idx'),
        ),
        migrations.AddIndex(
            model_name='ipaddress',
            index=models.Index(fields=['status'], name='network_man_status_bf5e96_idx'),
        ),
        migrations.AddIndex(
            model_name='ipaddress',
            index=models.Index(fields=['created_at'], name='network_man_created_6ff65e_idx'),
        ),
        migrations.AddIndex(
            model_name='hotspotuser',
            index=models.Index(fields=['mac'], name='network_man_mac_e3e7d2_idx'),
        ),
        migrations.AddIndex(
            model_name='hotspotuser',
            index=models.Index(fields=['session_id'], name='network_man_session_c71449_idx'),
        ),
        migrations.AddIndex(
            model_name='hotspotuser',
            index=models.Index(fields=['active'], name='network_man_active_7fe76e_idx'),
        ),
        migrations.AddIndex(
            model_name='hotspotuser',
            index=models.Index(fields=['client', 'active'], name='network_man_client__fb2726_idx'),
        ),
        migrations.AddIndex(
            model_name='hotspotuser',
            index=models.Index(fields=['router', 'active'], name='network_man_router__b243ef_idx'),
        ),
        migrations.AddIndex(
            model_name='hotspotuser',
            index=models.Index(fields=['quality_of_service'], name='network_man_quality_7dfec6_idx'),
        ),
        migrations.AddIndex(
            model_name='hotspotconfiguration',
            index=models.Index(fields=['router', 'ssid'], name='network_man_router__5491bc_idx'),
        ),
        migrations.AddIndex(
            model_name='hotspotconfiguration',
            index=models.Index(fields=['configuration_applied'], name='network_man_configu_81349c_idx'),
        ),
        migrations.AddIndex(
            model_name='diagnostictest',
            index=models.Index(fields=['router', 'test_type'], name='network_man_router__3edc63_idx'),
        ),
        migrations.AddIndex(
            model_name='diagnostictest',
            index=models.Index(fields=['created_at'], name='network_man_created_0e25c4_idx'),
        ),
        migrations.AddIndex(
            model_name='diagnostictest',
            index=models.Index(fields=['status'], name='network_man_status_9e4e86_idx'),
        ),
        migrations.AddIndex(
            model_name='diagnostictest',
            index=models.Index(fields=['client_ip'], name='network_man_client__f7c8af_idx'),
        ),
        migrations.AddIndex(
            model_name='bulkoperation',
            index=models.Index(fields=['operation_id'], name='network_man_operati_c61837_idx'),
        ),
        migrations.AddIndex(
            model_name='bulkoperation',
            index=models.Index(fields=['operation_type', 'status'], name='network_man_operati_68c787_idx'),
        ),
        migrations.AddIndex(
            model_name='bulkoperation',
            index=models.Index(fields=['initiated_by', 'started_at'], name='network_man_initiat_861f53_idx'),
        ),
        migrations.AddIndex(
            model_name='activationattempt',
            index=models.Index(fields=['payment_verified', 'success'], name='network_man_payment_1fd569_idx'),
        ),
        migrations.AddIndex(
            model_name='activationattempt',
            index=models.Index(fields=['router', 'attempted_at'], name='network_man_router__7e0471_idx'),
        ),
        migrations.AddIndex(
            model_name='activationattempt',
            index=models.Index(fields=['technician', 'attempted_at'], name='network_man_technic_5a55ce_idx'),
        ),
        migrations.AddIndex(
            model_name='routerauditlog',
            index=models.Index(fields=['router', 'action'], name='network_man_router__724105_idx'),
        ),
        migrations.AddIndex(
            model_name='routerauditlog',
            index=models.Index(fields=['timestamp'], name='network_man_timesta_00b970_idx'),
        ),
        migrations.AddIndex(
            model_name='routerauditlog',
            index=models.Index(fields=['user'], name='network_man_user_id_e715b6_idx'),
        ),
        migrations.AddIndex(
            model_name='routerauditlog',
            index=models.Index(fields=['action', 'timestamp'], name='network_man_action_6ace7a_idx'),
        ),
        migrations.AddIndex(
            model_name='routerauditlog',
            index=models.Index(fields=['status_code'], name='network_man_status__a409bf_idx'),
        ),
        migrations.AddIndex(
            model_name='routercallbackconfig',
            index=models.Index(fields=['router', 'event', 'is_active'], name='network_man_router__883742_idx'),
        ),
        migrations.AddIndex(
            model_name='routercallbackconfig',
            index=models.Index(fields=['is_active', 'event'], name='network_man_is_acti_577deb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='routercallbackconfig',
            unique_together={('router', 'event')},
        ),
        migrations.AddIndex(
            model_name='routerconnectiontest',
            index=models.Index(fields=['router', 'tested_at'], name='network_man_router__fe6672_idx'),
        ),
        migrations.AddIndex(
            model_name='routerconnectiontest',
            index=models.Index(fields=['success', 'tested_at'], name='network_man_success_f66dec_idx'),
        ),
        migrations.AddIndex(
            model_name='routerconnectiontest',
            index=models.Index(fields=['tested_by', 'tested_at'], name='network_man_tested__fdf9ca_idx'),
        ),
        migrations.AddIndex(
            model_name='routerhealthcheck',
            index=models.Index(fields=['router', 'timestamp'], name='network_man_router__54ecd1_idx'),
        ),
        migrations.AddIndex(
            model_name='routerhealthcheck',
            index=models.Index(fields=['health_score'], name='network_man_health__fb7749_idx'),
        ),
        migrations.AddIndex(
            model_name='routerhealthcheck',
            index=models.Index(fields=['is_online', 'timestamp'], name='network_man_is_onli_b67800_idx'),
        ),
        migrations.AddIndex(
            model_name='routersessionhistory',
            index=models.Index(fields=['recoverable', 'user_type'], name='network_man_recover_0961c6_idx'),
        ),
        migrations.AddIndex(
            model_name='routersessionhistory',
            index=models.Index(fields=['start_time', 'end_time'], name='network_man_start_t_819ce0_idx'),
        ),
        migrations.AddIndex(
            model_name='routersessionhistory',
            index=models.Index(fields=['router', 'start_time'], name='network_man_router__fded6b_idx'),
        ),
        migrations.AddIndex(
            model_name='routerstats',
            index=models.Index(fields=['router', 'timestamp'], name='network_man_router__114989_idx'),
        ),
        migrations.AddIndex(
            model_name='routerstats',
            index=models.Index(fields=['timestamp'], name='network_man_timesta_8d9446_idx'),
        ),
        migrations.AddIndex(
            model_name='speedtesthistory',
            index=models.Index(fields=['router', 'timestamp'], name='network_man_router__cb6752_idx'),
        ),
        migrations.AddIndex(
            model_name='speedtesthistory',
            index=models.Index(fields=['client_ip'], name='network_man_client__0d187c_idx'),
        ),
        migrations.AddIndex(
            model_name='speedtesthistory',
            index=models.Index(fields=['timestamp'], name='network_man_timesta_4a3075_idx'),
        ),
        migrations.AddIndex(
            model_name='subnet',
            index=models.Index(fields=['router', 'is_active'], name='network_man_router__6cd5a5_idx'),
        ),
        migrations.AddIndex(
            model_name='subnet',
            index=models.Index(fields=['network_address'], name='network_man_network_bd20e5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='subnet',
            unique_together={('router', 'network_address', 'netmask')},
        ),
    ]
