# Generated by Django 5.2.3 on 2025-09-19 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internet_plans', '0002_add_foreign_keys'),
        ('network_management', '0001_initial'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activationattempt',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='internet_plans.subscription'),
        ),
        migrations.AddField(
            model_name='hotspotuser',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='internet_plans.internetplan'),
        ),
        migrations.AddField(
            model_name='hotspotuser',
            name='transaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.transaction'),
        ),
    ]
