# Generated by Django 5.1.3 on 2025-04-10 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("network_management", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Router",
        ),
    ]
