# Generated by Django 5.2.3 on 2025-11-04 13:24

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_initial_mysql_fix'),
        ('internet_plans', '0004_remove_internetplan_features_and_more'),
        ('network_management', '0002_add_foreign_keys'),
        ('payments', '0002_add_foreign_keys'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('high_latency', 'High Latency'), ('packet_loss', 'High Packet Loss'), ('slow_speed', 'Slow Speed'), ('service_down', 'Service Down'), ('high_usage', 'High Bandwidth Usage'), ('security', 'Security Alert')], max_length=20)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PPPoEUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('service_name', models.CharField(blank=True, max_length=100)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('connected_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('disconnected_at', models.DateTimeField(blank=True, null=True)),
                ('data_used', models.BigIntegerField(default=0)),
                ('active', models.BooleanField(default=False)),
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('total_session_time', models.IntegerField(default=0, help_text='Total session time in seconds')),
                ('remaining_time', models.IntegerField(default=0, help_text='Remaining time in seconds')),
                ('last_activity', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-connected_at'],
            },
        ),
        migrations.CreateModel(
            name='RouterCallbackConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=100)),
                ('callback_url', models.URLField(max_length=500)),
                ('security_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('security_profile', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('retry_enabled', models.BooleanField(default=True)),
                ('max_retries', models.IntegerField(default=3)),
                ('timeout_seconds', models.IntegerField(default=30)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='bandwidthallocation',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='bandwidthusagehistory',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterModelOptions(
            name='diagnostictest',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='ipaddress',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='qosprofile',
            options={'ordering': ['priority', 'name']},
        ),
        migrations.AlterModelOptions(
            name='speedtesthistory',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AddField(
            model_name='activationattempt',
            name='user_type',
            field=models.CharField(choices=[('hotspot', 'Hotspot'), ('pppoe', 'PPPoE')], default='hotspot', max_length=10),
        ),
        migrations.AddField(
            model_name='bandwidthusagehistory',
            name='average_bandwidth',
            field=models.FloatField(blank=True, help_text='Average bandwidth in Mbps during this period', null=True),
        ),
        migrations.AddField(
            model_name='bandwidthusagehistory',
            name='peak_bandwidth',
            field=models.FloatField(blank=True, help_text='Peak bandwidth in Mbps during this period', null=True),
        ),
        migrations.AddField(
            model_name='dhcplease',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='diagnostictest',
            name='duration',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='diagnostictest',
            name='error_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='qosprofile',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='qosprofile',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='qosprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='router',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='router',
            name='pppoe_config',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='router',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='routerhealthcheck',
            name='system_metrics',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='routersessionhistory',
            name='user_type',
            field=models.CharField(choices=[('hotspot', 'Hotspot'), ('pppoe', 'PPPoE')], default='hotspot', max_length=10),
        ),
        migrations.AddField(
            model_name='speedtesthistory',
            name='packet_loss',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='speedtesthistory',
            name='test_mode',
            field=models.CharField(choices=[('quick', 'Quick'), ('full', 'Full')], default='full', max_length=20),
        ),
        migrations.AddField(
            model_name='subnet',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='diagnostictest',
            name='status',
            field=models.CharField(choices=[('idle', 'Idle'), ('running', 'Running'), ('success', 'Success'), ('error', 'Error'), ('timeout', 'Timeout')], default='idle', max_length=10),
        ),
        migrations.AlterField(
            model_name='diagnostictest',
            name='test_type',
            field=models.CharField(choices=[('ping', 'Ping'), ('traceroute', 'Traceroute'), ('speedtest', 'Speed Test'), ('dns', 'DNS Resolution'), ('packet_loss', 'Packet Loss'), ('health_check', 'Health Check'), ('port_scan', 'Port Scan')], max_length=20),
        ),
        migrations.AlterField(
            model_name='routersessionhistory',
            name='hotspot_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='session_history', to='network_management.hotspotuser'),
        ),
        migrations.AlterUniqueTogether(
            name='bandwidthallocation',
            unique_together={('client', 'ip_address', 'mac_address')},
        ),
        migrations.AlterUniqueTogether(
            name='dhcplease',
            unique_together={('ip_address', 'mac_address')},
        ),
        migrations.AlterUniqueTogether(
            name='subnet',
            unique_together={('router', 'network_address', 'netmask')},
        ),
        migrations.AddIndex(
            model_name='bandwidthallocation',
            index=models.Index(fields=['status'], name='network_man_status_2e6000_idx'),
        ),
        migrations.AddIndex(
            model_name='bandwidthallocation',
            index=models.Index(fields=['created_at'], name='network_man_created_048eba_idx'),
        ),
        migrations.AddIndex(
            model_name='bandwidthusagehistory',
            index=models.Index(fields=['timestamp'], name='network_man_timesta_1c706f_idx'),
        ),
        migrations.AddIndex(
            model_name='dhcplease',
            index=models.Index(fields=['ip_address', 'is_active'], name='network_man_ip_addr_40ae75_idx'),
        ),
        migrations.AddIndex(
            model_name='dhcplease',
            index=models.Index(fields=['mac_address'], name='network_man_mac_add_bb5f0c_idx'),
        ),
        migrations.AddIndex(
            model_name='dhcplease',
            index=models.Index(fields=['expires_at'], name='network_man_expires_3e9f46_idx'),
        ),
        migrations.AddIndex(
            model_name='diagnostictest',
            index=models.Index(fields=['status'], name='network_man_status_9e4e86_idx'),
        ),
        migrations.AddIndex(
            model_name='diagnostictest',
            index=models.Index(fields=['client_ip'], name='network_man_client__f7c8af_idx'),
        ),
        migrations.AddIndex(
            model_name='ipaddress',
            index=models.Index(fields=['router', 'status'], name='network_man_router__b095bf_idx'),
        ),
        migrations.AddIndex(
            model_name='ipaddress',
            index=models.Index(fields=['ip_address'], name='network_man_ip_addr_addf6c_idx'),
        ),
        migrations.AddIndex(
            model_name='ipaddress',
            index=models.Index(fields=['status'], name='network_man_status_bf5e96_idx'),
        ),
        migrations.AddIndex(
            model_name='ipaddress',
            index=models.Index(fields=['created_at'], name='network_man_created_6ff65e_idx'),
        ),
        migrations.AddIndex(
            model_name='qosprofile',
            index=models.Index(fields=['is_active'], name='network_man_is_acti_f149a9_idx'),
        ),
        migrations.AddIndex(
            model_name='router',
            index=models.Index(fields=['status', 'is_active'], name='network_man_status_982d51_idx'),
        ),
        migrations.AddIndex(
            model_name='router',
            index=models.Index(fields=['type'], name='network_man_type_184e84_idx'),
        ),
        migrations.AddIndex(
            model_name='speedtesthistory',
            index=models.Index(fields=['timestamp'], name='network_man_timesta_4a3075_idx'),
        ),
        migrations.AddIndex(
            model_name='subnet',
            index=models.Index(fields=['router', 'is_active'], name='network_man_router__6cd5a5_idx'),
        ),
        migrations.AddIndex(
            model_name='subnet',
            index=models.Index(fields=['network_address'], name='network_man_network_bd20e5_idx'),
        ),
        migrations.AddField(
            model_name='networkalert',
            name='related_test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='network_management.diagnostictest'),
        ),
        migrations.AddField(
            model_name='networkalert',
            name='router',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='network_management.router'),
        ),
        migrations.AddField(
            model_name='pppoeuser',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.client'),
        ),
        migrations.AddField(
            model_name='pppoeuser',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='internet_plans.internetplan'),
        ),
        migrations.AddField(
            model_name='pppoeuser',
            name='router',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pppoe_users', to='network_management.router'),
        ),
        migrations.AddField(
            model_name='pppoeuser',
            name='transaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.transaction'),
        ),
        migrations.AddField(
            model_name='routersessionhistory',
            name='pppoe_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='session_history', to='network_management.pppoeuser'),
        ),
        migrations.AddField(
            model_name='routercallbackconfig',
            name='router',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='callback_configs', to='network_management.router'),
        ),
        migrations.AddIndex(
            model_name='networkalert',
            index=models.Index(fields=['router', 'is_resolved'], name='network_man_router__8718be_idx'),
        ),
        migrations.AddIndex(
            model_name='networkalert',
            index=models.Index(fields=['severity'], name='network_man_severit_382b2e_idx'),
        ),
        migrations.AddIndex(
            model_name='networkalert',
            index=models.Index(fields=['created_at'], name='network_man_created_0b0353_idx'),
        ),
        migrations.AddIndex(
            model_name='pppoeuser',
            index=models.Index(fields=['username'], name='network_man_usernam_9220e1_idx'),
        ),
        migrations.AddIndex(
            model_name='pppoeuser',
            index=models.Index(fields=['session_id'], name='network_man_session_ee6e59_idx'),
        ),
        migrations.AddIndex(
            model_name='pppoeuser',
            index=models.Index(fields=['active'], name='network_man_active_7a047e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='routercallbackconfig',
            unique_together={('router', 'event')},
        ),
    ]
