# Generated by Django 5.1.3 on 2025-04-10 17:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("network_management", "0002_delete_router"),
    ]

    operations = [
        migrations.CreateModel(
            name="Router",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("ip", models.GenericIPAddressField()),
                ("port", models.PositiveIntegerField(default=8728)),
                ("username", models.CharField(default="admin", max_length=100)),
                ("password", models.CharField(blank=True, max_length=100)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("mikrotik", "Mikrotik"),
                            ("openwrt", "OpenWRT"),
                            ("cisco", "Cisco"),
                            ("generic", "Generic"),
                            ("tp-link", "TP-Link"),
                            ("ubiquiti", "Ubiquiti"),
                        ],
                        default="mikrotik",
                        max_length=20,
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("connected", "Connected"),
                            ("disconnected", "Disconnected"),
                            ("updating", "Updating"),
                            ("error", "Error"),
                        ],
                        default="disconnected",
                        max_length=20,
                    ),
                ),
                ("last_seen", models.DateTimeField(default=django.utils.timezone.now)),
                ("hotspot_config", models.JSONField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Router",
                "verbose_name_plural": "Routers",
            },
        ),
        migrations.CreateModel(
            name="HotspotUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("mac", models.CharField(max_length=17)),
                ("ip", models.GenericIPAddressField()),
                ("plan", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "connected_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("data_used", models.BigIntegerField(default=0)),
                (
                    "router",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hotspot_users",
                        to="network_management.router",
                    ),
                ),
            ],
            options={
                "verbose_name": "Hotspot User",
                "verbose_name_plural": "Hotspot Users",
            },
        ),
        migrations.CreateModel(
            name="RouterStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cpu", models.FloatField()),
                ("memory", models.FloatField()),
                ("clients", models.IntegerField()),
                ("uptime", models.CharField(max_length=10)),
                ("signal", models.IntegerField()),
                ("temperature", models.FloatField()),
                ("throughput", models.FloatField()),
                ("disk", models.FloatField()),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "router",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stats",
                        to="network_management.router",
                    ),
                ),
            ],
            options={
                "verbose_name": "Router Stats",
                "verbose_name_plural": "Router Stats",
            },
        ),
    ]
