# Generated by Django 5.2.3 on 2025-11-05 10:16

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_initial_mysql_fix'),
        ('internet_plans', '0004_remove_internetplan_features_and_more'),
        ('network_management', '0003_networkalert_pppoeuser_routercallbackconfig_and_more'),
        ('payments', '0002_add_foreign_keys'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('operation_type', models.CharField(choices=[('health_check', 'Health Check'), ('restart', 'Restart'), ('update_firmware', 'Update Firmware'), ('backup_config', 'Backup Configuration'), ('restore_config', 'Restore Configuration')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('partial', 'Partial Success')], default='pending', max_length=20)),
                ('results', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='RouterAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('restart', 'Restart'), ('configure', 'Configure'), ('status_change', 'Status Change'), ('user_activation', 'User Activation'), ('user_deactivation', 'User Deactivation')], max_length=20)),
                ('description', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddField(
            model_name='activationattempt',
            name='payment_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='activationattempt',
            name='transaction_reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='activationattempt',
            name='verification_method',
            field=models.CharField(choices=[('automatic', 'Automatic'), ('manual', 'Manual')], default='automatic', max_length=20),
        ),
        migrations.AddField(
            model_name='hotspotuser',
            name='bandwidth_used',
            field=models.JSONField(default=dict, help_text='Upload/download usage in bytes'),
        ),
        migrations.AddField(
            model_name='hotspotuser',
            name='device_info',
            field=models.JSONField(default=dict, help_text='Device type, OS, browser info'),
        ),
        migrations.AddField(
            model_name='hotspotuser',
            name='quality_of_service',
            field=models.CharField(choices=[('standard', 'Standard'), ('premium', 'Premium'), ('basic', 'Basic')], default='standard', max_length=20),
        ),
        migrations.AddField(
            model_name='pppoeuser',
            name='bandwidth_used',
            field=models.JSONField(default=dict, help_text='Upload/download usage in bytes'),
        ),
        migrations.AddField(
            model_name='pppoeuser',
            name='pppoe_service_type',
            field=models.CharField(choices=[('standard', 'Standard'), ('business', 'Business'), ('premium', 'Premium')], default='standard', max_length=50),
        ),
        migrations.AddField(
            model_name='router',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='router',
            name='firmware_version',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='router',
            name='max_clients',
            field=models.PositiveIntegerField(default=50, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)]),
        ),
        migrations.AddField(
            model_name='router',
            name='ssid',
            field=models.CharField(blank=True, default='SurfZone-WiFi', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='routerhealthcheck',
            name='critical_alerts',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='routerhealthcheck',
            name='health_score',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='routerhealthcheck',
            name='performance_metrics',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='routersessionhistory',
            name='recoverable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='routersessionhistory',
            name='recovered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='routersessionhistory',
            name='recovery_attempted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='routerstats',
            name='download_speed',
            field=models.FloatField(default=0, help_text='in Mbps', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='routerstats',
            name='hotspot_clients',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='routerstats',
            name='pppoe_clients',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='routerstats',
            name='upload_speed',
            field=models.FloatField(default=0, help_text='in Mbps', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='router',
            name='callback_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='routercallbackconfig',
            name='event',
            field=models.CharField(choices=[('payment_received', 'Payment Received'), ('user_connected', 'User Connected'), ('user_disconnected', 'User Disconnected'), ('router_offline', 'Router Offline'), ('router_online', 'Router Online'), ('bandwidth_exceeded', 'Bandwidth Exceeded'), ('session_expired', 'Session Expired'), ('suspicious_activity', 'Suspicious Activity'), ('health_alert', 'Health Alert')], max_length=100),
        ),
        migrations.AlterField(
            model_name='routersessionhistory',
            name='disconnected_reason',
            field=models.CharField(blank=True, choices=[('router_reboot', 'Router Reboot'), ('power_outage', 'Power Outage'), ('manual_disconnect', 'Manual Disconnect'), ('session_timeout', 'Session Timeout'), ('router_switch', 'Router Switch'), ('payment_expired', 'Payment Expired'), ('bandwidth_exceeded', 'Bandwidth Exceeded'), ('suspicious_activity', 'Suspicious Activity')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='routerstats',
            name='connected_clients_count',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='routerstats',
            name='cpu',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='routerstats',
            name='disk',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='routerstats',
            name='memory',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='routerstats',
            name='signal',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='routerstats',
            name='temperature',
            field=models.FloatField(blank=True, help_text='in °C', null=True),
        ),
        migrations.AlterField(
            model_name='routerstats',
            name='throughput',
            field=models.FloatField(help_text='in Mbps', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='routerstats',
            name='uptime',
            field=models.CharField(max_length=50),
        ),
        migrations.AddIndex(
            model_name='activationattempt',
            index=models.Index(fields=['payment_verified', 'success'], name='network_man_payment_1fd569_idx'),
        ),
        migrations.AddIndex(
            model_name='hotspotuser',
            index=models.Index(fields=['client', 'active'], name='network_man_client__fb2726_idx'),
        ),
        migrations.AddIndex(
            model_name='pppoeuser',
            index=models.Index(fields=['client', 'active'], name='network_man_client__97b468_idx'),
        ),
        migrations.AddIndex(
            model_name='router',
            index=models.Index(fields=['ssid'], name='network_man_ssid_e90f3d_idx'),
        ),
        migrations.AddIndex(
            model_name='routercallbackconfig',
            index=models.Index(fields=['router', 'event', 'is_active'], name='network_man_router__883742_idx'),
        ),
        migrations.AddIndex(
            model_name='routerhealthcheck',
            index=models.Index(fields=['router', 'timestamp'], name='network_man_router__54ecd1_idx'),
        ),
        migrations.AddIndex(
            model_name='routerhealthcheck',
            index=models.Index(fields=['health_score'], name='network_man_health__fb7749_idx'),
        ),
        migrations.AddIndex(
            model_name='routersessionhistory',
            index=models.Index(fields=['recoverable', 'user_type'], name='network_man_recover_0961c6_idx'),
        ),
        migrations.AddIndex(
            model_name='routersessionhistory',
            index=models.Index(fields=['start_time', 'end_time'], name='network_man_start_t_819ce0_idx'),
        ),
        migrations.AddIndex(
            model_name='routerstats',
            index=models.Index(fields=['router', 'timestamp'], name='network_man_router__114989_idx'),
        ),
        migrations.AddField(
            model_name='bulkoperation',
            name='initiated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bulkoperation',
            name='routers',
            field=models.ManyToManyField(related_name='bulk_operations', to='network_management.router'),
        ),
        migrations.AddField(
            model_name='routerauditlog',
            name='router',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='network_management.router'),
        ),
        migrations.AddField(
            model_name='routerauditlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='bulkoperation',
            index=models.Index(fields=['operation_id'], name='network_man_operati_c61837_idx'),
        ),
        migrations.AddIndex(
            model_name='bulkoperation',
            index=models.Index(fields=['operation_type', 'status'], name='network_man_operati_68c787_idx'),
        ),
        migrations.AddIndex(
            model_name='routerauditlog',
            index=models.Index(fields=['router', 'action'], name='network_man_router__724105_idx'),
        ),
        migrations.AddIndex(
            model_name='routerauditlog',
            index=models.Index(fields=['timestamp'], name='network_man_timesta_00b970_idx'),
        ),
        migrations.AddIndex(
            model_name='routerauditlog',
            index=models.Index(fields=['user'], name='network_man_user_id_e715b6_idx'),
        ),
    ]
