# Generated by Django 5.1.3 on 2025-04-11 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
        ("internet_plans", "0001_initial"),
        ("network_management", "0003_initial"),
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="hotspotuser",
            options={},
        ),
        migrations.AlterModelOptions(
            name="router",
            options={},
        ),
        migrations.AlterModelOptions(
            name="routerstats",
            options={},
        ),
        migrations.RemoveField(
            model_name="hotspotuser",
            name="name",
        ),
        migrations.AddField(
            model_name="hotspotuser",
            name="active",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="hotspotuser",
            name="client",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="account.client",
            ),
        ),
        migrations.AddField(
            model_name="hotspotuser",
            name="transaction",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="payments.transaction",
            ),
        ),
        migrations.AlterField(
            model_name="hotspotuser",
            name="plan",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="internet_plans.internetplan",
            ),
        ),
        migrations.AlterField(
            model_name="router",
            name="type",
            field=models.CharField(
                choices=[("mikrotik", "Mikrotik")], default="mikrotik", max_length=20
            ),
        ),
    ]
