# Generated by Django 5.2.3 on 2025-11-10 12:26

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network_management', '0004_bulkoperation_routerauditlog_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='router',
            name='hotspot_config',
        ),
        migrations.RemoveField(
            model_name='router',
            name='pppoe_config',
        ),
        migrations.AlterField(
            model_name='hotspotuser',
            name='quality_of_service',
            field=models.CharField(choices=[('Residential', 'Residential'), ('Business', 'Business'), ('Promotional', 'Promotional'), ('Enterprise', 'Enterprise')], default='standard', max_length=20),
        ),
        migrations.CreateModel(
            name='HotspotConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ssid', models.CharField(default='SurfZone-WiFi', max_length=100)),
                ('landing_page_file', models.FileField(blank=True, null=True, upload_to='hotspot_pages/')),
                ('redirect_url', models.URLField(default='http://captive.surfzone.local')),
                ('bandwidth_limit', models.CharField(default='10M', max_length=20)),
                ('session_timeout', models.IntegerField(default=60, help_text='Session timeout in minutes')),
                ('auth_method', models.CharField(choices=[('universal', 'Universal'), ('mac', 'MAC Address'), ('voucher', 'Voucher'), ('social', 'Social Login')], default='universal', max_length=20)),
                ('enable_splash_page', models.BooleanField(default=True)),
                ('allow_social_login', models.BooleanField(default=False)),
                ('enable_bandwidth_shaping', models.BooleanField(default=True)),
                ('log_user_activity', models.BooleanField(default=True)),
                ('max_users', models.IntegerField(default=50, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)])),
                ('welcome_message', models.TextField(blank=True, null=True)),
                ('terms_conditions_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('router', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotspot_configurations', to='network_management.router')),
            ],
            options={
                'verbose_name': 'Hotspot Configuration',
                'verbose_name_plural': 'Hotspot Configurations',
            },
        ),
        migrations.CreateModel(
            name='PPPoEConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_pool_name', models.CharField(default='pppoe-pool-1', max_length=50)),
                ('service_name', models.CharField(blank=True, max_length=100, null=True)),
                ('mtu', models.IntegerField(default=1492, validators=[django.core.validators.MinValueValidator(576), django.core.validators.MaxValueValidator(1500)])),
                ('dns_servers', models.CharField(default='8.8.8.8,1.1.1.1', max_length=100)),
                ('bandwidth_limit', models.CharField(default='10M', max_length=20)),
                ('auth_methods', models.CharField(choices=[('all', 'All Methods'), ('pap', 'PAP Only'), ('chap', 'CHAP Only'), ('mschap', 'MS-CHAP Only')], default='all', max_length=20)),
                ('enable_pap', models.BooleanField(default=True)),
                ('enable_chap', models.BooleanField(default=True)),
                ('enable_mschap', models.BooleanField(default=True)),
                ('idle_timeout', models.IntegerField(default=300, help_text='Idle timeout in seconds')),
                ('session_timeout', models.IntegerField(default=0, help_text='Session timeout in seconds (0 = unlimited)')),
                ('default_profile', models.CharField(default='default', max_length=50)),
                ('interface', models.CharField(default='bridge', max_length=50)),
                ('ip_range_start', models.GenericIPAddressField(default='192.168.100.10')),
                ('ip_range_end', models.GenericIPAddressField(default='192.168.100.200')),
                ('service_type', models.CharField(choices=[('standard', 'Standard'), ('business', 'Business'), ('premium', 'Premium')], default='standard', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('router', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pppoe_configurations', to='network_management.router')),
            ],
            options={
                'verbose_name': 'PPPoE Configuration',
                'verbose_name_plural': 'PPPoE Configurations',
            },
        ),
    ]
