# Generated by Django 5.2.3 on 2025-11-24 14:12

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_initial_mysql_fix'),
        ('internet_plans', '0005_remove_subscription_transaction_and_more'),
        ('network_management', '0005_remove_router_hotspot_config_and_more'),
        ('payments', '0010_alter_taxconfiguration_tax_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RouterConnectionTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('success', models.BooleanField(default=False)),
                ('response_time', models.FloatField(blank=True, help_text='Response time in seconds', null=True)),
                ('system_info', models.JSONField(blank=True, default=dict, help_text='System information from router')),
                ('error_messages', models.JSONField(blank=True, default=list, help_text='List of error messages')),
                ('tested_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-tested_at'],
            },
        ),
        migrations.AddField(
            model_name='activationattempt',
            name='technician',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='activationattempt',
            name='workflow_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bulkoperation',
            name='parameters',
            field=models.JSONField(blank=True, default=dict, help_text='Operation parameters'),
        ),
        migrations.AddField(
            model_name='bulkoperation',
            name='progress',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='hotspotconfiguration',
            name='configuration_applied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hotspotconfiguration',
            name='configuration_errors',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='hotspotconfiguration',
            name='dns_servers',
            field=models.CharField(default='8.8.8.8,1.1.1.1', max_length=100),
        ),
        migrations.AddField(
            model_name='hotspotconfiguration',
            name='idle_timeout',
            field=models.IntegerField(default=300, help_text='Idle timeout in seconds'),
        ),
        migrations.AddField(
            model_name='hotspotconfiguration',
            name='ip_pool',
            field=models.CharField(default='192.168.100.10-192.168.100.200', max_length=100),
        ),
        migrations.AddField(
            model_name='hotspotconfiguration',
            name='last_configuration_attempt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hotspotconfiguration',
            name='rate_limit',
            field=models.CharField(default='10M/10M', max_length=50),
        ),
        migrations.AddField(
            model_name='hotspotuser',
            name='average_signal_strength',
            field=models.IntegerField(blank=True, help_text='Average signal strength in dBm', null=True),
        ),
        migrations.AddField(
            model_name='hotspotuser',
            name='connection_quality',
            field=models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor')], default='good', max_length=20),
        ),
        migrations.AddField(
            model_name='pppoeconfiguration',
            name='configuration_applied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pppoeconfiguration',
            name='configuration_errors',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='pppoeconfiguration',
            name='last_configuration_attempt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pppoeuser',
            name='connection_quality',
            field=models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor')], default='good', max_length=20),
        ),
        migrations.AddField(
            model_name='pppoeuser',
            name='connection_uptime',
            field=models.IntegerField(default=0, help_text='Connection uptime in seconds'),
        ),
        migrations.AddField(
            model_name='router',
            name='average_response_time',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='router',
            name='configuration_status',
            field=models.CharField(choices=[('not_configured', 'Not Configured'), ('configured', 'Configured'), ('partially_configured', 'Partially Configured'), ('configuration_failed', 'Configuration Failed')], default='not_configured', max_length=25),
        ),
        migrations.AddField(
            model_name='router',
            name='configuration_template',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='router',
            name='configuration_type',
            field=models.CharField(blank=True, choices=[('hotspot', 'Hotspot'), ('pppoe', 'PPPoE'), ('both', 'Both'), ('vpn', 'VPN')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='router',
            name='connection_status',
            field=models.CharField(choices=[('connected', 'Connected'), ('disconnected', 'Disconnected'), ('testing', 'Testing'), ('authentication_failed', 'Authentication Failed'), ('connection_failed', 'Connection Failed')], default='disconnected', max_length=25),
        ),
        migrations.AddField(
            model_name='router',
            name='connection_success_rate',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='router',
            name='last_configuration_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='router',
            name='last_connection_test',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='router',
            name='last_technician_workflow',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='router',
            name='vpn_configuration',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='router',
            name='vpn_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='router',
            name='vpn_type',
            field=models.CharField(blank=True, choices=[('openvpn', 'OpenVPN'), ('wireguard', 'WireGuard'), ('sstp', 'SSTP')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='router',
            name='workflow_status',
            field=models.CharField(blank=True, help_text='Status of last technician workflow', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='routerhealthcheck',
            name='vpn_status',
            field=models.JSONField(blank=True, default=dict, help_text='VPN connection status and metrics'),
        ),
        migrations.AddField(
            model_name='routersessionhistory',
            name='average_signal_strength',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='routersessionhistory',
            name='connection_quality',
            field=models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor')], default='good', max_length=20),
        ),
        migrations.AddField(
            model_name='routerstats',
            name='vpn_connections',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='routerstats',
            name='vpn_throughput',
            field=models.FloatField(default=0, help_text='VPN throughput in Mbps'),
        ),
        migrations.AlterField(
            model_name='bulkoperation',
            name='operation_type',
            field=models.CharField(choices=[('health_check', 'Health Check'), ('restart', 'Restart'), ('update_firmware', 'Update Firmware'), ('backup_config', 'Backup Configuration'), ('restore_config', 'Restore Configuration'), ('test_connection', 'Test Connection'), ('auto_configure', 'Auto Configure'), ('technician_workflow', 'Technician Workflow'), ('vpn_configuration', 'VPN Configuration')], max_length=20),
        ),
        migrations.AlterField(
            model_name='hotspotconfiguration',
            name='ssid',
            field=models.CharField(default='SurfZone-WiFi', help_text='Dynamic SSID for the hotspot. Can be customized per router.', max_length=100),
        ),
        migrations.AlterField(
            model_name='pppoeconfiguration',
            name='service_name',
            field=models.CharField(blank=True, help_text='PPPoE service name. Leave blank for auto-generation.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='router',
            name='ssid',
            field=models.CharField(blank=True, default='SurfZone-WiFi', help_text='Dynamic SSID for hotspot configuration. Leave blank for auto-generation.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='routerauditlog',
            name='action',
            field=models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('restart', 'Restart'), ('configure', 'Configure'), ('status_change', 'Status Change'), ('user_activation', 'User Activation'), ('user_deactivation', 'User Deactivation'), ('connection_test', 'Connection Test'), ('technician_workflow', 'Technician Workflow'), ('vpn_configuration', 'VPN Configuration'), ('bulk_operation', 'Bulk Operation')], max_length=20),
        ),
        migrations.AlterField(
            model_name='routercallbackconfig',
            name='event',
            field=models.CharField(choices=[('payment_received', 'Payment Received'), ('user_connected', 'User Connected'), ('user_disconnected', 'User Disconnected'), ('router_offline', 'Router Offline'), ('router_online', 'Router Online'), ('bandwidth_exceeded', 'Bandwidth Exceeded'), ('session_expired', 'Session Expired'), ('suspicious_activity', 'Suspicious Activity'), ('health_alert', 'Health Alert'), ('vpn_status_change', 'VPN Status Change'), ('technician_workflow_completed', 'Technician Workflow Completed')], max_length=100),
        ),
        migrations.AlterField(
            model_name='routersessionhistory',
            name='disconnected_reason',
            field=models.CharField(blank=True, choices=[('router_reboot', 'Router Reboot'), ('power_outage', 'Power Outage'), ('manual_disconnect', 'Manual Disconnect'), ('session_timeout', 'Session Timeout'), ('router_switch', 'Router Switch'), ('payment_expired', 'Payment Expired'), ('bandwidth_exceeded', 'Bandwidth Exceeded'), ('suspicious_activity', 'Suspicious Activity'), ('vpn_reconnect', 'VPN Reconnect')], max_length=100, null=True),
        ),
        migrations.AddIndex(
            model_name='activationattempt',
            index=models.Index(fields=['router', 'attempted_at'], name='network_man_router__7e0471_idx'),
        ),
        migrations.AddIndex(
            model_name='activationattempt',
            index=models.Index(fields=['technician', 'attempted_at'], name='network_man_technic_5a55ce_idx'),
        ),
        migrations.AddIndex(
            model_name='bulkoperation',
            index=models.Index(fields=['initiated_by', 'started_at'], name='network_man_initiat_861f53_idx'),
        ),
        migrations.AddIndex(
            model_name='hotspotconfiguration',
            index=models.Index(fields=['router', 'ssid'], name='network_man_router__5491bc_idx'),
        ),
        migrations.AddIndex(
            model_name='hotspotconfiguration',
            index=models.Index(fields=['configuration_applied'], name='network_man_configu_81349c_idx'),
        ),
        migrations.AddIndex(
            model_name='hotspotuser',
            index=models.Index(fields=['router', 'active'], name='network_man_router__b243ef_idx'),
        ),
        migrations.AddIndex(
            model_name='hotspotuser',
            index=models.Index(fields=['quality_of_service'], name='network_man_quality_7dfec6_idx'),
        ),
        migrations.AddIndex(
            model_name='pppoeconfiguration',
            index=models.Index(fields=['router', 'service_name'], name='network_man_router__1bd03c_idx'),
        ),
        migrations.AddIndex(
            model_name='pppoeconfiguration',
            index=models.Index(fields=['configuration_applied'], name='network_man_configu_c54aaf_idx'),
        ),
        migrations.AddIndex(
            model_name='pppoeuser',
            index=models.Index(fields=['router', 'active'], name='network_man_router__8409c5_idx'),
        ),
        migrations.AddIndex(
            model_name='pppoeuser',
            index=models.Index(fields=['pppoe_service_type'], name='network_man_pppoe_s_f31cc4_idx'),
        ),
        migrations.AddIndex(
            model_name='router',
            index=models.Index(fields=['connection_status'], name='network_man_connect_5fe1af_idx'),
        ),
        migrations.AddIndex(
            model_name='router',
            index=models.Index(fields=['configuration_status'], name='network_man_configu_397454_idx'),
        ),
        migrations.AddIndex(
            model_name='router',
            index=models.Index(fields=['last_connection_test'], name='network_man_last_co_bb438a_idx'),
        ),
        migrations.AddIndex(
            model_name='router',
            index=models.Index(fields=['vpn_enabled', 'vpn_type'], name='network_man_vpn_ena_78425c_idx'),
        ),
        migrations.AddIndex(
            model_name='routerauditlog',
            index=models.Index(fields=['action', 'timestamp'], name='network_man_action_6ace7a_idx'),
        ),
        migrations.AddIndex(
            model_name='routercallbackconfig',
            index=models.Index(fields=['is_active', 'event'], name='network_man_is_acti_577deb_idx'),
        ),
        migrations.AddIndex(
            model_name='routerhealthcheck',
            index=models.Index(fields=['is_online', 'timestamp'], name='network_man_is_onli_b67800_idx'),
        ),
        migrations.AddIndex(
            model_name='routersessionhistory',
            index=models.Index(fields=['router', 'start_time'], name='network_man_router__fded6b_idx'),
        ),
        migrations.AddIndex(
            model_name='routerstats',
            index=models.Index(fields=['timestamp'], name='network_man_timesta_8d9446_idx'),
        ),
        migrations.AddField(
            model_name='routerconnectiontest',
            name='router',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connection_tests', to='network_management.router'),
        ),
        migrations.AddField(
            model_name='routerconnectiontest',
            name='tested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='routerconnectiontest',
            index=models.Index(fields=['router', 'tested_at'], name='network_man_router__fe6672_idx'),
        ),
        migrations.AddIndex(
            model_name='routerconnectiontest',
            index=models.Index(fields=['success', 'tested_at'], name='network_man_success_f66dec_idx'),
        ),
        migrations.AddIndex(
            model_name='routerconnectiontest',
            index=models.Index(fields=['tested_by', 'tested_at'], name='network_man_tested__fdf9ca_idx'),
        ),
    ]
