# Generated by Django 5.2.3 on 2025-11-24 15:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network_management', '0006_routerconnectiontest_activationattempt_technician_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='routerauditlog',
            name='status_code',
            field=models.IntegerField(blank=True, help_text='HTTP status code for API operations', null=True),
        ),
        migrations.AddIndex(
            model_name='routerauditlog',
            index=models.Index(fields=['status_code'], name='network_man_status__a409bf_idx'),
        ),
    ]
