# Generated by Django 5.2.3 on 2025-11-24 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network_management', '0007_routerauditlog_status_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routerauditlog',
            name='action',
            field=models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('restart', 'Restart'), ('configure', 'Configure'), ('status_change', 'Status Change'), ('user_activation', 'User Activation'), ('user_deactivation', 'User Deactivation'), ('connection_test', 'Connection Test'), ('technician_workflow', 'Technician Workflow'), ('vpn_configuration', 'VPN Configuration'), ('bulk_operation', 'Bulk Operation'), ('audit_cleanup', 'Audit Cleanup'), ('audit_export', 'Audit Export')], max_length=20),
        ),
        migrations.AlterField(
            model_name='routerauditlog',
            name='router',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='network_management.router'),
        ),
    ]
