# Generated by Django 5.2.3 on 2026-01-22 14:54

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientOperation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_id', models.UUIDField(db_index=True, help_text='Client ID from Authentication app')),
                ('client_type', models.CharField(db_index=True, help_text='Client type (hotspot/pppoe)', max_length=20)),
                ('operation_type', models.CharField(choices=[('plan_purchase', 'Plan Purchase'), ('plan_renewal', 'Plan Renewal'), ('plan_upgrade', 'Plan Upgrade'), ('payment_verification', 'Payment Verification'), ('activation_request', 'Activation Request'), ('usage_update', 'Usage Update'), ('client_support', 'Client Support'), ('profile_update', 'Profile Update'), ('credentials_reset', 'Credentials Reset')], db_index=True, max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('priority', models.IntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High'), (4, 'Urgent'), (5, 'Critical')], db_index=True, default=2)),
                ('title', models.CharField(help_text='Operation title', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Detailed description')),
                ('source_platform', models.CharField(choices=[('hotspot_portal', 'Hotspot Captive Portal'), ('pppoe_portal', 'PPPoE Client Portal'), ('dashboard', 'Admin Dashboard'), ('api', 'API Integration'), ('router', 'Router Integration')], db_index=True, help_text='Platform where operation originated', max_length=50)),
                ('requested_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('started_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('result_data', models.JSONField(blank=True, default=dict, help_text='Operation result data')),
                ('error_message', models.TextField(blank=True, null=True)),
                ('error_details', models.JSONField(blank=True, default=dict)),
                ('sla_due_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('sla_breached', models.BooleanField(db_index=True, default=False)),
                ('current_step', models.PositiveIntegerField(default=1)),
                ('total_steps', models.PositiveIntegerField(default=1)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Client Operation',
                'verbose_name_plural': 'Client Operations',
                'ordering': ['-priority', '-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_id', models.UUIDField(blank=True, db_index=True, help_text='Client ID from Authentication app', null=True)),
                ('internet_plan_id', models.UUIDField(db_index=True, help_text='Plan ID from Internet Plans app')),
                ('client_type', models.CharField(choices=[('hotspot_client', 'Hotspot Client'), ('pppoe_client', 'PPPoE Client')], db_index=True, help_text='Type of client (hotspot or pppoe)', max_length=20)),
                ('access_method', models.CharField(choices=[('hotspot', 'Hotspot (WiFi)'), ('pppoe', 'PPPoE (Ethernet)')], db_index=True, default='hotspot', help_text='Access method for this subscription', max_length=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_payment', 'Pending Payment'), ('pending_activation', 'Pending Activation'), ('active', 'Active'), ('expired', 'Expired'), ('suspended', 'Suspended'), ('cancelled', 'Cancelled'), ('failed', 'Activation Failed'), ('processing', 'Processing')], db_index=True, default='draft', help_text='Subscription status', max_length=20)),
                ('router_id', models.IntegerField(blank=True, db_index=True, help_text='Router ID from Network Management app', null=True)),
                ('hotspot_mac_address', models.CharField(blank=True, db_index=True, help_text='MAC address for hotspot clients', max_length=17, null=True)),
                ('pppoe_username', models.CharField(blank=True, db_index=True, help_text='PPPoE username (auto-generated)', max_length=50, null=True)),
                ('pppoe_password', models.CharField(blank=True, help_text='PPPoE password (auto-generated)', max_length=100, null=True)),
                ('payment_reference', models.CharField(blank=True, db_index=True, help_text='Payment transaction reference', max_length=100, null=True)),
                ('payment_method', models.CharField(blank=True, help_text='Payment method used (mpesa_till, mpesa_paybill, paypal, bank)', max_length=50, null=True)),
                ('payment_confirmed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('start_date', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('scheduled_activation', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('used_data_bytes', models.BigIntegerField(default=0)),
                ('used_time_seconds', models.BigIntegerField(default=0)),
                ('data_limit_bytes', models.BigIntegerField(default=0)),
                ('time_limit_seconds', models.BigIntegerField(default=0)),
                ('activation_attempts', models.PositiveIntegerField(default=0)),
                ('activation_successful', models.BooleanField(default=False)),
                ('activation_error', models.TextField(blank=True, null=True)),
                ('activation_completed_at', models.DateTimeField(blank=True, null=True)),
                ('auto_renew', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('last_usage_update', models.DateTimeField(blank=True, null=True)),
                ('parent_subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renewals', to='service_operations.subscription')),
            ],
            options={
                'verbose_name': 'Subscription',
                'verbose_name_plural': 'Subscriptions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OperationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('operation_type', models.CharField(choices=[('subscription_creation', 'Subscription Creation'), ('subscription_activation', 'Subscription Activation'), ('payment_processing', 'Payment Processing'), ('router_integration', 'Router Integration'), ('client_operation', 'Client Operation'), ('system_maintenance', 'System Maintenance'), ('error', 'Error'), ('warning', 'Warning'), ('info', 'Information')], db_index=True, max_length=50)),
                ('severity', models.CharField(choices=[('debug', 'Debug'), ('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], db_index=True, default='info', max_length=20)),
                ('description', models.TextField(help_text='Log description')),
                ('details', models.JSONField(blank=True, default=dict, help_text='Additional details')),
                ('error_message', models.TextField(blank=True, null=True)),
                ('error_traceback', models.TextField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, max_length=100, null=True)),
                ('duration_ms', models.PositiveIntegerField(default=0, help_text='Duration in milliseconds')),
                ('source_module', models.CharField(db_index=True, max_length=100)),
                ('source_function', models.CharField(db_index=True, max_length=100)),
                ('source_ip', models.GenericIPAddressField(blank=True, db_index=True, null=True)),
                ('request_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('correlation_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('client_operation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operation_logs', to='service_operations.clientoperation')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operation_logs', to='service_operations.subscription')),
            ],
            options={
                'verbose_name': 'Operation Log',
                'verbose_name_plural': 'Operation Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='clientoperation',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_operations', to='service_operations.subscription'),
        ),
        migrations.CreateModel(
            name='ActivationQueue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('priority', models.IntegerField(choices=[(1, 'Lowest'), (2, 'Low'), (3, 'Normal'), (4, 'High'), (5, 'Highest'), (6, 'Emergency')], db_index=True, default=3)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('retrying', 'Retrying'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('activation_type', models.CharField(choices=[('initial', 'Initial Activation'), ('renewal', 'Renewal Activation'), ('reactivation', 'Reactivation'), ('upgrade', 'Upgrade Activation'), ('emergency', 'Emergency Activation')], default='initial', max_length=20)),
                ('processor_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('started_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('max_retries', models.PositiveIntegerField(default=3)),
                ('next_retry_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_error_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('error_details', models.JSONField(blank=True, default=dict)),
                ('estimated_duration_seconds', models.PositiveIntegerField(default=60)),
                ('actual_duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('router_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('network_config', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activation_requests', to='service_operations.subscription')),
            ],
            options={
                'verbose_name': 'Activation Queue',
                'verbose_name_plural': 'Activation Queue',
                'ordering': ['-priority', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='UsageTracking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data_used_bytes', models.BigIntegerField(default=0)),
                ('time_used_seconds', models.BigIntegerField(default=0)),
                ('session_start', models.DateTimeField(default=django.utils.timezone.now)),
                ('session_end', models.DateTimeField(default=django.utils.timezone.now)),
                ('peak_data_rate', models.IntegerField(default=0)),
                ('avg_data_rate', models.IntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_records', to='service_operations.subscription')),
            ],
            options={
                'verbose_name': 'Usage Tracking',
                'verbose_name_plural': 'Usage Tracking Records',
                'ordering': ['-session_start'],
            },
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['client_id', 'is_active'], name='service_ope_client__a192f9_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['client_type', 'status'], name='service_ope_client__9accdf_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['access_method', 'status'], name='service_ope_access__197ab3_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['router_id', 'status'], name='service_ope_router__96f805_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['payment_reference'], name='service_ope_payment_49b520_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['status', 'is_active'], name='service_ope_status_50d864_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['end_date', 'status'], name='service_ope_end_dat_2c38d9_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['hotspot_mac_address', 'status'], name='service_ope_hotspot_b6fd56_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['pppoe_username', 'status'], name='service_ope_pppoe_u_d182f1_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['client_id', 'status', 'is_active'], name='service_ope_client__9c438b_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['client_type', 'access_method', 'status'], name='service_ope_client__c430cf_idx'),
        ),
        migrations.AddIndex(
            model_name='operationlog',
            index=models.Index(fields=['operation_type', 'severity'], name='service_ope_operati_ccfdb9_idx'),
        ),
        migrations.AddIndex(
            model_name='operationlog',
            index=models.Index(fields=['subscription', 'created_at'], name='service_ope_subscri_873b29_idx'),
        ),
        migrations.AddIndex(
            model_name='operationlog',
            index=models.Index(fields=['source_module', 'created_at'], name='service_ope_source__0b6933_idx'),
        ),
        migrations.AddIndex(
            model_name='operationlog',
            index=models.Index(fields=['request_id'], name='service_ope_request_1551a1_idx'),
        ),
        migrations.AddIndex(
            model_name='operationlog',
            index=models.Index(fields=['correlation_id'], name='service_ope_correla_6df1fe_idx'),
        ),
        migrations.AddIndex(
            model_name='clientoperation',
            index=models.Index(fields=['client_id', 'status'], name='service_ope_client__222fb3_idx'),
        ),
        migrations.AddIndex(
            model_name='clientoperation',
            index=models.Index(fields=['client_type', 'operation_type'], name='service_ope_client__76155c_idx'),
        ),
        migrations.AddIndex(
            model_name='clientoperation',
            index=models.Index(fields=['source_platform', 'status'], name='service_ope_source__d6f241_idx'),
        ),
        migrations.AddIndex(
            model_name='clientoperation',
            index=models.Index(fields=['status', 'priority'], name='service_ope_status_7874b4_idx'),
        ),
        migrations.AddIndex(
            model_name='clientoperation',
            index=models.Index(fields=['sla_due_at', 'sla_breached'], name='service_ope_sla_due_5bb374_idx'),
        ),
        migrations.AddIndex(
            model_name='activationqueue',
            index=models.Index(fields=['status', 'priority'], name='service_ope_status_171308_idx'),
        ),
        migrations.AddIndex(
            model_name='activationqueue',
            index=models.Index(fields=['subscription', 'status'], name='service_ope_subscri_0df10f_idx'),
        ),
        migrations.AddIndex(
            model_name='activationqueue',
            index=models.Index(fields=['router_id', 'status'], name='service_ope_router__b27855_idx'),
        ),
        migrations.AddIndex(
            model_name='activationqueue',
            index=models.Index(fields=['next_retry_at', 'status'], name='service_ope_next_re_226348_idx'),
        ),
        migrations.AddIndex(
            model_name='activationqueue',
            index=models.Index(fields=['created_at', 'status'], name='service_ope_created_7dcd7d_idx'),
        ),
        migrations.AddIndex(
            model_name='usagetracking',
            index=models.Index(fields=['subscription', 'session_start'], name='service_ope_subscri_144d32_idx'),
        ),
        migrations.AddIndex(
            model_name='usagetracking',
            index=models.Index(fields=['session_start', 'session_end'], name='service_ope_session_1c1ada_idx'),
        ),
    ]
