# Generated by Django 5.1.3 on 2025-01-28 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MonthlyFinancial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "month",
                    models.CharField(
                        choices=[
                            ("Jan", "January"),
                            ("Feb", "February"),
                            ("Mar", "March"),
                            ("Apr", "April"),
                            ("May", "May"),
                            ("Jun", "June"),
                            ("Jul", "July"),
                            ("Aug", "August"),
                            ("Sept", "September"),
                            ("Oct", "October"),
                            ("Nov", "November"),
                            ("Dec", "December"),
                        ],
                        max_length=4,
                    ),
                ),
                (
                    "targeted_revenue",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "projected_revenue",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("income", models.DecimalField(decimal_places=2, max_digits=10)),
                ("profit", models.DecimalField(decimal_places=2, max_digits=10)),
                ("expenses", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name="UsageReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("month", models.CharField(max_length=3)),
                ("used_data", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "remaining_data",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("active_users", models.PositiveIntegerField()),
                ("inactive_users", models.PositiveIntegerField()),
                ("network_performance", models.IntegerField()),
            ],
        ),
    ]
