name: Build and Publish image to Docker Hub

on:
  push:
    branches: ["main"]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    strategy:
      matrix:
        include:
          - service: backend
            context: ./Backend
            image: codongo/interlink_backend
          - service: dashboard
            context: ./Frontend/Dashboard
            image: codongo/interlink_dashboard
          - service: landingpage
            context: ./Frontend/Landingpage
            image: codongo/interlink_landingpage
          - service: nginx
            context: ./nginx
            image: codongo/interlink_nginx

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push ${{ matrix.service }}
        run: |
          set -e
          docker buildx build \
            --push \
            --tag ${{ matrix.image }}:latest \
            --tag ${{ matrix.image }}:${{ github.sha }} \
            --cache-to type=gha \
            --cache-from type=gha \
            ${{ matrix.context }}
